

CREATE  PROCEDURE [dbo].[spRIS_GetSamples]
	@Event_Id NVARCHAR(4000)
AS

/*---------------------------------------------------------------------------------------------------------------------
    This procedure retrieves sample UDEs for comma separated list of material lot ids
  
    Date         Ver/Build   Author              Story/Defect        Remarks
    11-Sep-2020  001         Evgeniy Kim							 Clean up and format
    13-Jan-2021	 002		 Evgeniy Kim & Suman					 Increase EventId size to allow more samples to be displayed


---------------------------------------------------------------------------------------------------------------------
    NOTES: 
    1. If a sample contains a test with an AutoGeneratedSample variable id, then the sample was manually created
	   by the user and can be deleted from UI.
    
    QUESTIONS:
    1. 


---------------------------------------------------------------------------------------------------------------------*/
IF(@Event_Id IS NULL)
BEGIN
	ROLLBACK;
	RAISERROR(N'@Event_Id is not valid.', 16, 1);
	RETURN;
END

DECLARE @eventTable TABLE 
(
	Event_Id INT
);

DECLARE @tOutput TABLE
(
	Event_Id	INT,
	UDE_Id	INT NOT NULL,
	UDE_Desc	NVARCHAR(255) NOT NULL,
	Comment_Id	INT,
	[User_Id]	INT,
	End_Time	DATETIME,
	PU_Id		INT,
	Var_Id	INT
);

INSERT INTO @eventTable SELECT * FROM string_split(@Event_Id, ',');

BEGIN TRANSACTION
BEGIN

INSERT INTO @tOutput SELECT 
	UDE.Event_Id,                 
	UDE.UDE_Id,
	UDE.UDE_Desc,                               
	UDE.Comment_Id,
	UDE.[User_Id]  ,
	UDE.End_Time,
	UDE.PU_Id,
	NULL
FROM	User_Defined_Events UDE WITH(NOLOCK)
INNER JOIN Events e WITH(NOLOCK)
ON	UDE.Event_Id = e.Event_Id 
JOIN @eventTable t
ON	t.Event_Id = ude.Event_Id;
	
UPDATE T SET T.Var_Id = VB.Var_Id
FROM	@tOutput t
JOIN	Tests test WITH(NOLOCK)
ON		test.Event_Id = T.UDE_Id 
JOIN	Variables_Base VB WITH(NOLOCK)
ON		VB.Var_Id = test.Var_Id
AND	VB.Var_Desc = N'AutoGeneratedSample';
	
SELECT  
	event_Id,
	UDE_Id,
	UDE_Desc,       
	comment_id,
	user_id  ,
	End_Time,
	PU_Id,
	Var_Id
FROM  @tOutput 
ORDER BY UDE_Id ASC;

END
COMMIT;