
CREATE PROCEDURE [dbo].[spRIS_DeleteSamples]
	@UDE_Id INT,
	@UserId INT 

AS

/*---------------------------------------------------------------------------------------------------------------------
    This procedure attempts to delete a UDE (sample) by UDE_Id
  
    Date         Ver/Build   Author              Story/Defect        Remarks
    30-Dec-2019  001         Nausheen Khan       US391927            Initial Development
    03-Aug-2020  002         Evgeniy Kim         DE140031            Added extra check to make sure a sample cannot be 
																	 deleted if created by the sampling engine
    04-Aug-2020	 003		 Evgeniy Kim	     DE140031            Should be AutoGeneratedSample, not AutoGeneratedComment

---------------------------------------------------------------------------------------------------------------------
    NOTES:  
    
    QUESTIONS:

---------------------------------------------------------------------------------------------------------------------*/

 DECLARE	@Event_Id		INT,
			@PUId			INT,
			@EventSubTypeId INT,
			@err_message	NVARCHAR(255);

IF(@UDE_Id IS NULL AND @UserId IS NULL)
BEGIN
	SET @err_message = 'UDE_Id and UserId are not valid (NULL)';
	RAISERROR (@err_message, 16, 1);
	RETURN;
END

IF NOT EXISTS (
	SELECT * FROM User_Defined_Events UDE WITH(NOLOCK)
	JOIN	Tests T WITH(NOLOCK)
	ON		UDE.UDE_Id = T.Event_Id
	JOIN	Variables_Base VB WITH(NOLOCK)
	ON		VB.Var_Id = T.Var_Id
	AND		VB.Var_desc = N'AutoGeneratedSample'
	AND		UDE.UDE_Id = @UDE_Id)
BEGIN
	SELECT Error = 'Auto generated sample cannot be deleted';
	RETURN @@ERROR; 
END

IF EXISTS(SELECT * FROM Dbo.User_Defined_Events WHERE UDE_Id = @UDE_Id) 
BEGIN
	SELECT @Event_Id = event_id, @EventSubTypeId = Event_Subtype_Id, @PUId = PU_Id
    FROM DBO.User_Defined_Events WHERE UDE_Id =@UDE_Id;

	EXECUTE [dbo].[spServer_DBMgrUpdUserEvent]
        0,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        @EventSubTypeId,
        @PUId,
        NULL,
        @UDE_Id ,
        @UserId,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        3,
        NULL,
        NULL,
        NULL,
        @Event_Id ,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL;
END
ELSE   
BEGIN
	SELECT Error = N'UDE_Id/Sample Id does not exist';  
	RETURN @@ERROR;  
END

GRANT EXECUTE ON [dbo].[spRIS_DeleteSamples] TO [ComXClient]