CREATE PROCEDURE dbo.spSDK_IncomingWasteEvent412
 	 -- Input Parameters
 	 @WriteDirect 	  	  	 BIT,
 	 @UpdateClientOnly 	  	 BIT,
 	 @LineName 	  	  	  	 nvarchar(50),
 	 @UnitName 	  	  	  	 nvarchar(50),
 	 @EventName 	  	  	 nvarchar(25),
 	 @Timestamp 	  	  	 DATETIME,
 	 @Amount 	  	  	  	  	 REAL,
 	 @Cause1 	  	  	  	  	 nvarchar(50),
 	 @Cause2 	  	  	  	  	 nvarchar(50),
 	 @Cause3 	  	  	  	  	 nvarchar(50),
 	 @Cause4 	  	  	  	  	 nvarchar(50),
 	 @Action1 	  	  	  	 nvarchar(50),
 	 @Action2 	  	  	  	 nvarchar(50),
 	 @Action3 	  	  	  	 nvarchar(50),
 	 @Action4 	  	  	  	 nvarchar(50),
 	 @Measurement 	  	 nvarchar(50),
 	 @ResearchOpenDate 	  	 DATETIME,
 	 @ResearchCloseDate 	 DATETIME,
 	 @ResearchStatus 	  	 nvarchar(50),
 	 @ResearchUserName 	 nvarchar(50),
 	 @SourceLineName 	  	 nvarchar(50),
 	 @SourceUnitName 	  	 nvarchar(50),
 	 @WasteType 	  	  	  	 nvarchar(50),
 	 @UserId 	  	  	  	  	 INT,
 	 @Fault 	  	  	  	  	 nvarchar(50),
 	 -- Input/Output Parameters
 	 @WasteId 	  	  	  	  	 INT OUTPUT,
 	 @TransactionType 	  	 INT OUTPUT,
 	 -- Output Parameters
 	 @PUId 	  	  	  	  	  	 INT OUTPUT,
 	 @EventId 	  	  	  	  	 INT OUTPUT,
 	 @Cause1Id 	  	  	  	 INT OUTPUT,
 	 @Cause2Id 	  	  	  	 INT OUTPUT,
 	 @Cause3Id 	  	  	  	 INT OUTPUT,
 	 @Cause4Id 	  	  	  	 INT OUTPUT,
 	 @CauseCommentId 	  	 INT OUTPUT,
 	 @Action1Id 	  	  	  	 INT OUTPUT,
 	 @Action2Id 	  	  	  	 INT OUTPUT,
 	 @Action3Id 	  	  	  	 INT OUTPUT,
 	 @Action4Id 	  	  	  	 INT OUTPUT,
 	 @ActionCommentId 	  	 INT OUTPUT,
 	 @WEMTId 	  	  	  	  	 INT OUTPUT,
 	 @ResearchStatusId 	  	 INT OUTPUT,
 	 @ResearchUserId 	  	 INT OUTPUT,
 	 @ResearchCommentId 	 INT OUTPUT,
 	 @SrcPUId 	  	  	  	  	 INT OUTPUT,
 	 @WETId 	  	  	  	  	 INT OUTPUT,
 	 @WEFaultId 	  	  	  	 INT OUTPUT
AS
DECLARE @RC INT
DECLARE @ESignatureId INT
EXECUTE @RC =spSDK_IncomingWasteEvent 	  	 @WriteDirect,@UpdateClientOnly,@LineName,@UnitName,@EventName,
 	 @Timestamp,@Amount,@Cause1,@Cause2,@Cause3,
 	 @Cause4,@Action1,@Action2,@Action3,@Action4,
 	 @Measurement,@ResearchOpenDate,@ResearchCloseDate,@ResearchStatus,@ResearchUserName,
 	 @SourceLineName,@SourceUnitName,@WasteType,@UserId,@Fault,
 	 Null,--@UserGeneral1,
 	 Null,--@UserGeneral2,
 	 Null,--@UserGeneral3,
 	 Null,--@UserGeneral4,
 	 Null,--@UserGeneral5,
 	 @WasteId OUTPUT,@TransactionType OUTPUT,@ESignatureId OUTPUT,@PUId 	 OUTPUT,@EventId 	 OUTPUT,
 	 @Cause1Id 	 OUTPUT,@Cause2Id 	 OUTPUT,@Cause3Id 	 OUTPUT,@Cause4Id 	 OUTPUT,@CauseCommentId 	 OUTPUT,
 	 @Action1Id OUTPUT,@Action2Id OUTPUT,@Action3Id OUTPUT,@Action4Id OUTPUT,@ActionCommentId OUTPUT,
 	 @WEMTId OUTPUT,@ResearchStatusId OUTPUT,@ResearchUserId OUTPUT,@ResearchCommentId OUTPUT,@SrcPUId OUTPUT,
 	 @WETId OUTPUT,@WEFaultId OUTPUT
RETURN(@RC)
