CREATE PROCEDURE [dbo].[spLocal_QV_Next_PQM_OOW]
@OutputValue VARCHAR (25) NULL OUTPUT, @Typo_id INT NULL, @InC_id1 INT NULL, @InC_id2 INT NULL, @InC_id3 INT NULL, @InC_id4 INT NULL, @InC_id5 INT NULL, @InC_id6 INT NULL, @Rule VARCHAR (30) NULL, @Temps VARCHAR (30) NULL, @Cause VARCHAR (30) NULL, @Repair VARCHAR (30) NULL, @PadsPurged VARCHAR (30) NULL, @OOS1 VARCHAR (30) NULL, @OOS2 VARCHAR (30) NULL, @OOS3 VARCHAR (30) NULL, @OOS4 VARCHAR (30) NULL, @OOS5 VARCHAR (30) NULL, @OOS6 VARCHAR (30) NULL, @Final_OOS VARCHAR (30) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


