CREATE PROCEDURE [dbo].[spLocal_QV_FireReEval]
@OutputValue VARCHAR (25) NULL OUTPUT, @PU_Id INT NULL, @TimeStamp VARCHAR (30) NULL, @RuleViolated VARCHAR (30) NULL, @TimeDev VARCHAR (30) NULL, @CloseVal VARCHAR (30) NULL, @NameVar VARCHAR (30) NULL, @IdVar VARCHAR (30) NULL, @TargetVal VARCHAR (30) NULL, @USVal VARCHAR (30) NULL, @LSVal VARCHAR (30) NULL, @EI_TIME VARCHAR (25) NULL, @EI_NAME VARCHAR (25) NULL, @EI_RV VARCHAR (25) NULL, @EI_VARID VARCHAR (25) NULL, @EI_TARGET VARCHAR (30) NULL, @EI_US VARCHAR (25) NULL, @EI_LS VARCHAR (25) NULL, @Puid_ReEvalSheet VARCHAR (5) NULL, @ei_name2 VARCHAR (30) NULL, @NameVar2 VARCHAR (30) NULL, @Sample VARCHAR (30) NULL, @EI_Alarm VARCHAR (30) NULL, @ThisVarID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


