CREATE PROCEDURE [dbo].[spLocal_QV_InitializeValues]
@dtmTimestamp DATETIME NULL, @intVarIDTC INT NULL, @vcrEIName VARCHAR (25) NULL, @vcrEIName2 VARCHAR (30) NULL, @vcrEITime VARCHAR (25) NULL, @vcrEIVarID VARCHAR (25) NULL, @vcrEIRV VARCHAR (25) NULL, @vcrEIVT VARCHAR (25) NULL, @vcrEITarget VARCHAR (25) NULL, @vcrEILS VARCHAR (25) NULL, @vcrEIUS VARCHAR (25) NULL, @vcrEILC VARCHAR (25) NULL, @vcrEIUC VARCHAR (25) NULL, @vcrEILW VARCHAR (25) NULL, @vcrEIUW VARCHAR (25) NULL, @vcrEIVE VARCHAR (25) NULL, @vcrEISS VARCHAR (30) NULL, @vcrOOS VARCHAR (30) NULL OUTPUT, @vcrOOC VARCHAR (30) NULL OUTPUT, @vcrOOW VARCHAR (30) NULL OUTPUT, @vcrOOT VARCHAR (30) NULL OUTPUT, @intRSUserID INT NULL OUTPUT, @intIsTCChecked INT NULL OUTPUT, @intPLID INT NULL OUTPUT, @intCountNull INT NULL OUTPUT, @intPUIDReest INT NULL OUTPUT, @intVarIDName1 INT NULL OUTPUT, @intVarIDName2 INT NULL OUTPUT, @intVarIDTime INT NULL OUTPUT, @intVarIDId INT NULL OUTPUT, @intVarIDRV INT NULL OUTPUT, @intVarIDVT INT NULL OUTPUT, @intVarIDTARGET INT NULL OUTPUT, @intVarIDLS INT NULL OUTPUT, @intVarIDUS INT NULL OUTPUT, @intVarIDLC INT NULL OUTPUT, @intVarIDUC INT NULL OUTPUT, @intVarIDLW INT NULL OUTPUT, @intVarIDUW INT NULL OUTPUT, @intVarIDVE INT NULL OUTPUT, @intVarIDSS INT NULL OUTPUT, @intSecond INT NULL OUTPUT, @intReesSheetID INT NULL OUTPUT, @dtmTimestamp1 DATETIME NULL OUTPUT, @intColCount INT NULL OUTPUT
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


