CREATE PROCEDURE [dbo].[spLocal_QV_InControl]
@OutputValue VARCHAR (25) NULL OUTPUT, @Average VARCHAR (30) NULL, @US VARCHAR (30) NULL, @LS VARCHAR (30) NULL, @UC VARCHAR (30) NULL, @LC VARCHAR (30) NULL, @UW VARCHAR (30) NULL, @LW VARCHAR (30) NULL, @Rule VARCHAR (30) NULL, @target VARCHAR (30) NULL, @VE VARCHAR (30) NULL, @VT VARCHAR (30) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


