CREATE PROCEDURE [dbo].[spLocal_QV_NextStep]
@OutputValue VARCHAR (25) NULL OUTPUT, @SG1OOS VARCHAR (30) NULL, @SG1IC VARCHAR (30) NULL, @SG2IC VARCHAR (30) NULL, @SG3IC VARCHAR (30) NULL, @SG4IC VARCHAR (30) NULL, @SG5IC VARCHAR (30) NULL, @SG6IC VARCHAR (30) NULL, @DevStat VARCHAR (30) NULL, @SG2OOS VARCHAR (30) NULL, @SG3OOS VARCHAR (30) NULL, @SG4OOS VARCHAR (30) NULL, @SG5OOS VARCHAR (30) NULL, @SG6OOS VARCHAR (30) NULL, @Next VARCHAR (30) NULL, @Rule VARCHAR (30) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


