CREATE PROCEDURE [dbo].[spLocal_QX_Quality_Checks]
@vcrOutputValue VARCHAR (25) NULL OUTPUT, @intPUID INT NULL, @dtmTimestamp DATETIME NULL, @intVarIDTC INT NULL, @vcrEIName VARCHAR (25) NULL, @vcrEIName2 VARCHAR (30) NULL, @vcrEITime VARCHAR (25) NULL, @vcrEIVarID VARCHAR (25) NULL, @vcrEIRV VARCHAR (25) NULL, @vcrEIVT VARCHAR (25) NULL, @vcrEITarget VARCHAR (25) NULL, @vcrEILS VARCHAR (25) NULL, @vcrEIUS VARCHAR (25) NULL, @vcrEILC VARCHAR (25) NULL, @vcrEIUC VARCHAR (25) NULL, @vcrEILW VARCHAR (25) NULL, @vcrEIUW VARCHAR (25) NULL, @vcrEIVE VARCHAR (25) NULL, @vcrEISS VARCHAR (30) NULL, @vcrCalcName VARCHAR (30) NULL, @vcrEINameAttr VARCHAR (25) NULL, @vcrEIName2Attr VARCHAR (30) NULL, @vcrEITimeAttr VARCHAR (25) NULL, @vcrEIVarIDAttr VARCHAR (25) NULL, @vcrEIFailAttr VARCHAR (25) NULL, @vcrEITypeAttr VARCHAR (25) NULL, @vcrEIDevAttr VARCHAR (25) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


