CREATE PROCEDURE [dbo].[spLocal_QA_Fire_Reeval]
@OutputValue VARCHAR (25) NULL OUTPUT, @PU_Id INT NULL, @TimeStamp DATETIME NULL, @CloseVal VARCHAR (30) NULL, @TimeDev DATETIME NULL, @NameVar VARCHAR (30) NULL, @NameVar2 VARCHAR (30) NULL, @Failure VARCHAR (30) NULL, @EI_TIME VARCHAR (25) NULL, @EI_NAME VARCHAR (25) NULL, @EI_NAME2 VARCHAR (25) NULL, @EI_Fail VARCHAR (25) NULL, @EI_Alarm VARCHAR (30) NULL, @ThisVarID INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


