CREATE PROCEDURE dbo.spServer_AMgrGetAlarmCache
@MaxAlarms int
AS
declare @@ATDId int,
        @@Alarm_Id int,
        @@Ack int,
        @@Alarm_Desc nVarChar(1000),
        @@End_Time datetime,
        @@Ack_On datetime,
        @@Research_Open_Date datetime,
        @@Research_Close_Date datetime,
        @@Start_Time datetime,
        @@Cause1 int,
        @@ATD_Id int,
        @@Alarm_Type_Id int,
        @@Cause4 int,
        @@Key_Id int,
        @@Ack_By int,
        @@Action2 int,
        @@Cause2 int,
        @@Cause3 int,
        @@Action_Comment_Id int,
        @@Cause_Comment_Id int,
        @@Action1 int,
        @@Research_Comment_Id int,
        @@Action3 int,
        @@Action4 int,
        @@Duration int,
        @@Research_User_Id int,
        @@Research_Status_Id int,
        @@Source_PU_Id int,
        @@User_Id int,
        @@Cutoff tinyint,
        @@Max_Result nVarChar(30),
        @@Min_Result nVarChar(30),
        @@Start_Result nVarChar(30),
        @@End_Result nVarChar(30),
        @@Modified_On datetime,
        @@ATSRD_Id int,
        @@ATVRD_Id int,
        @@Path_Id int,
        @count int,
 	 @@var_id int
Declare @AGACResults Table(Alarm_Id int,
                          Ack int NULL,
                          Alarm_Desc nVarChar(1000) COLLATE DATABASE_DEFAULT NULL,
                          End_Time datetime NULL,
                          Ack_On datetime NULL,
                          Research_Open_Date datetime NULL,
                          Research_Close_Date datetime NULL,
                          Start_Time datetime NULL,
                          Cause1 int NULL,
                          ATD_Id int NULL,
                          Alarm_Type_Id int NULL,
                          Cause4 int NULL,
                          Key_Id int NULL,
                          Ack_By int NULL,
                          Action2 int NULL,
                          Cause2 int NULL,
                          Cause3 int NULL,
                          Action_Comment_Id int NULL,
                          Cause_Comment_Id int NULL,
                          Action1 int NULL,
                          Research_Comment_Id int NULL,
                          Action3 int NULL,
                          Action4 int NULL,
                          Duration int NULL,
                          Research_User_Id int NULL,
                          Research_Status_Id int NULL,
                          Source_PU_Id int NULL,
                          User_Id int NULL,
                          Cutoff tinyint NULL,
                          Max_Result nVarChar(30) COLLATE DATABASE_DEFAULT NULL,
                          Min_Result nVarChar(30) COLLATE DATABASE_DEFAULT NULL,
                          Start_Result nVarChar(30) COLLATE DATABASE_DEFAULT NULL,
                          End_Result nVarChar(30) COLLATE DATABASE_DEFAULT NULL,
                          Modified_On datetime NULL,
                          ATSRD_Id int NULL,
                          ATVRD_Id int NULL,
                          Path_Id int NULL)
Declare The_Cursor INSENSITIVE CURSOR
For (Select distinct atd_id, key_id, alarm_type_id from Alarms) 
For Read Only
Open The_Cursor  
Fetch_Loop:
  Fetch Next From The_Cursor Into @@atdid, @@var_id, @@alarm_type_id
  If (@@Fetch_Status = 0)
  Begin
    Declare Inner_Cursor INSENSITIVE CURSOR
    For Select Alarm_Id,
               Ack,
               Alarm_Desc,
               End_Time,
               Ack_On,
               Research_Open_Date,
               Research_Close_Date,
               Start_Time,
               Cause1,
               Alarm_Type_Id,
               Cause4,
               Key_Id,
               Ack_By,
               Action2,
               Cause2,
               Cause3,
               Action_Comment_Id,
               Cause_Comment_Id,
               Action1,
               Research_Comment_Id,
               Action3,
               Action4,
               Duration,
               Research_User_Id,
               Research_Status_Id,
               Source_PU_Id,
               User_Id,
               Cutoff,
               Max_Result,
               Min_Result,
               Start_Result,
               End_Result,
               Modified_On,
               ATSRD_Id,
               ATVRD_Id,
               Path_Id
               from Alarms where atd_id = @@atdid and key_id = @@var_id and alarm_type_id = @@alarm_type_id order by start_time desc
    For Read Only
    Open Inner_Cursor  
 	 select @count = 0
Inner_Loop:
      Fetch Next From Inner_Cursor Into 
 	                                   @@Alarm_Id,
                                      @@Ack,
                                      @@Alarm_Desc,
                                      @@End_Time,
                                      @@Ack_On,
                                      @@Research_Open_Date,
                                      @@Research_Close_Date,
                                      @@Start_Time,
                                      @@Cause1,
                                      @@Alarm_Type_Id,
                                      @@Cause4,
                                      @@Key_Id,
                                      @@Ack_By,
                                      @@Action2,
                                      @@Cause2,
                                      @@Cause3,
                                      @@Action_Comment_Id,
                                      @@Cause_Comment_Id,
                                      @@Action1,
                                      @@Research_Comment_Id,
                                      @@Action3,
                                      @@Action4,
                                      @@Duration,
                                      @@Research_User_Id,
                                      @@Research_Status_Id,
                                      @@Source_PU_Id,
                                      @@User_Id,
                                      @@Cutoff,
                                      @@Max_Result,
                                      @@Min_Result,
                                      @@Start_Result,
                                      @@End_Result,
                                      @@Modified_On,
                                      @@ATSRD_Id,
                                      @@ATVRD_Id,
                                      @@Path_Id
      If (@@Fetch_Status = 0)
      Begin
        insert into @AGACResults (ATD_Id,
 	  	         	  	  	  	  	  	  	           Alarm_Id,
                                  Ack,
                                  Alarm_Desc,
                                  End_Time,
                                  Ack_On,
                                  Research_Open_Date,
                                  Research_Close_Date,
                                  Start_Time,
                                  Cause1,
                                  Alarm_Type_Id,
                                  Cause4,
                                  Key_Id,
                                  Ack_By,
                                  Action2,
                                  Cause2,
                                  Cause3,
                                  Action_Comment_Id,
                                  Cause_Comment_Id,
                                  Action1,
                                  Research_Comment_Id,
                                  Action3,
                                  Action4,
                                  Duration,
                                  Research_User_Id,
                                  Research_Status_Id,
                                  Source_PU_Id,
                                  User_Id,
                                  Cutoff,
                                  Max_Result,
                                  Min_Result,
                                  Start_Result,
                                  End_Result,
                                  Modified_On,
                                  ATSRD_Id, 
                                  ATVRD_Id,
                                  Path_Id) 
 	  	  	 values (@@ATDid,
 	  	  	  	  	  	  	  	  	  	  	  	         @@Alarm_Id,
                                @@Ack,
                                @@Alarm_Desc,
                                @@End_Time,
                                @@Ack_On,
                                @@Research_Open_Date,
                                @@Research_Close_Date,
                                @@Start_Time,
                                @@Cause1,
                                @@Alarm_Type_Id,
                                @@Cause4,
                                @@Key_Id,
                                @@Ack_By,
                                @@Action2,
                                @@Cause2,
                                @@Cause3,
                                @@Action_Comment_Id,
                                @@Cause_Comment_Id,
                                @@Action1,
                                @@Research_Comment_Id,
                                @@Action3,
                                @@Action4,
                                @@Duration,
                                @@Research_User_Id,
                                @@Research_Status_Id,
                                @@Source_PU_Id,
                                @@User_Id,
                                @@Cutoff,
                                @@Max_Result,
                                @@Min_Result,
                                @@Start_Result,
                                @@End_Result,
                                @@Modified_On,
                                @@ATSRD_Id,
                                @@ATVRD_Id,
                                @@Path_Id)
        select @Count = @Count + 1
 	  	 if @Count < @MaxAlarms
 	  	   Goto Inner_Loop
 	   end
    Close Inner_Cursor
    Deallocate Inner_Cursor
 	 
    Goto Fetch_Loop
  End
Close The_Cursor
Deallocate The_Cursor
select ATD_Id,
       Alarm_Id,
       Ack,
       Alarm_Desc,
       End_Time,
       Ack_On,
       Research_Open_Date,
       Research_Close_Date,
       Start_Time,
       Cause1,
       Alarm_Type_Id,
       Cause4,
       Key_Id,
       Ack_By,
       Action2,
       Cause2,
       Cause3,
       Action_Comment_Id,
       Cause_Comment_Id,
       Action1,
       Research_Comment_Id,
       Action3,
       Action4,
       Duration,
       Research_User_Id,
       Research_Status_Id,
       Source_PU_Id,
       User_Id,
       Cutoff,
       Max_Result,
       Min_Result,
       Start_Result,
       End_Result,
       Modified_On,
       ATSRD_Id,
       ATVRD_Id,
       Path_Id 
 	    from @AGACResults 
