CREATE PROCEDURE [dbo].[spServer_DBMgrUpdEventWithDetails]
  @Event_Id         int OUTPUT,           
  @Event_Num        nVarChar(50) OUTPUT, 
  @PU_Id            int,                  
  @TimeStamp        Datetime,             
  @Applied_Product  int,                  
  @Source_Event     int,                  
  @Event_Status     int,              
  @TransType int,              
  @TransNum int, 	  	  	 
  @UserId int, 	  	  	  	 
  @CommentId int, 	  	  	 
  @EventSubtypeId int, 	  	  	 
  @TestingStatus int OUTPUT, 	  	  	 
  @StartTime Datetime, 	  	 
  @EntryOn Datetime OUTPUT, 	  	 
  @Conformance int  OUTPUT,
  @TestPctComplete int  OUTPUT,
  @SecondUserId int, 
  @ApproverUserId int, 
  @ApproverReasonId int, 
  @UserReasonId int, 
  @UserSignoffId int, 
  @Extended_Info nVarChar(255), 
  @SignatureId int, 
 	 @ED_AltEventNum 	 nVarChar(100) = NULL OUTPUT,
 	 @ED_InitialDimX 	 float = NULL OUTPUT,
 	 @ED_InitialDimY 	 float = NULL OUTPUT,
 	 @ED_InitialDimZ 	 float = NULL OUTPUT,
 	 @ED_InitialDimA 	 float = NULL OUTPUT,
 	 @ED_FinalDimX 	  	 float = NULL OUTPUT,
 	 @ED_FinalDimY 	  	 float = NULL OUTPUT,
 	 @ED_FinalDimZ 	  	 float = NULL OUTPUT,
 	 @ED_FinalDimA 	  	 float = NULL OUTPUT,
 	 @ED_OrientationX 	 float = NULL OUTPUT,
 	 @ED_OrientationY 	 float = NULL OUTPUT,
 	 @ED_OrientationZ 	 float = NULL OUTPUT,
 	 @ED_OrderId 	  	 int = NULL OUTPUT,
 	 @ED_OrderLineId 	 int = NULL OUTPUT,
 	 @ED_PPId 	  	  	 int = NULL OUTPUT,
 	 @ED_PPSetupDetailId int = NULL OUTPUT,
 	 @ED_ShipmentId 	  	 int = NULL OUTPUT,
 	 @ED_CommentId 	  	 int = NULL OUTPUT,
 	 @ED_EntryOn 	  	 datetime = NULL OUTPUT,
  @ED_SignatureId int = NULL ,
 	 @ED_ProductDefId 	 Int = NULL
AS
Declare
 	 @EventReturnCode int,
 	 @DetailReturnCode int,
 	 @Future1 	  	 nVarChar(100),
 	 @Future2 	  	 int, 
 	 @Future3 	  	 int, 
 	 @Future4 	  	 int, 
 	 @Future6 	  	 int
Execute @EventReturnCode = spServer_DBMgrUpdEvent
  @Event_Id         OUTPUT,           
  @Event_Num        OUTPUT, 
  @PU_Id,                  
  @TimeStamp,             
  @Applied_Product,                  
  @Source_Event,                  
  @Event_Status,              
  @TransType,              
  @TransNum, 	  	  	 
  @UserId, 	  	  	  	 
  @CommentId, 	  	  	 
  @EventSubtypeId, 	  	  	 
  @TestingStatus output, 	  	  	 
  @StartTime, 	  	 
  @EntryOn 	  	  	  	  	 OUTPUT, 	  	 
  1, -- ReturnResultSet
  @Conformance 	  	  	 OUTPUT,
  @TestPctComplete 	 OUTPUT,
  @SecondUserId,
  @ApproverUserId,
  @ApproverReasonId,
  @UserReasonId,
  @UserSignoffId,
  @Extended_Info,
  1, -- SendEventPost
  @SignatureId 
  If (@EventReturnCode Not In (1,2,3,4))
    Return(@EventReturnCode)
 	 Execute @DetailReturnCode = spServer_DBMgrUpdEventDet
 	  	 @UserId,
 	  	 @Event_Id,
 	  	 @PU_Id,
 	  	 NULL,
 	  	 @TransType,
 	  	 @TransNum,
 	  	 @ED_AltEventNum 	  	  	 OUTPUT,
 	  	 @Future2 	  	  	  	  	  	 OUTPUT, 
 	  	 @ED_InitialDimX 	  	  	 OUTPUT,
 	  	 @ED_InitialDimY 	  	  	 OUTPUT,
 	  	 @ED_InitialDimZ 	  	  	 OUTPUT,
 	  	 @ED_InitialDimA 	  	  	 OUTPUT,
 	  	 @ED_FinalDimX 	  	  	  	 OUTPUT,
 	  	 @ED_FinalDimY 	  	  	  	 OUTPUT,
 	  	 @ED_FinalDimZ 	  	  	  	 OUTPUT,
 	  	 @ED_FinalDimA 	  	  	  	 OUTPUT,
 	  	 @ED_OrientationX 	  	 OUTPUT,
 	  	 @ED_OrientationY 	  	 OUTPUT,
 	  	 @ED_OrientationZ 	  	 OUTPUT,
 	  	 @Future3 	  	  	  	  	  	 OUTPUT, 
 	  	 @Future4 	  	  	  	  	  	 OUTPUT, 
 	  	 @ED_OrderId 	  	  	  	  	 OUTPUT,
 	  	 @ED_OrderLineId 	  	  	 OUTPUT,
 	  	 @ED_PPId 	  	  	  	  	  	 OUTPUT,
 	  	 @ED_PPSetupDetailId OUTPUT,
 	  	 @ED_ShipmentId 	  	  	 OUTPUT,
 	  	 @ED_CommentId 	  	  	  	 OUTPUT,
 	  	 @ED_EntryOn 	  	  	  	  	 OUTPUT,
 	  	 @TimeStamp 	  	  	  	  	 OUTPUT,
 	  	 @Future6 	  	  	  	  	  	 OUTPUT,
 	  	 @ED_SignatureId,
 	  	 @ED_ProductDefId 	 
  If (@DetailReturnCode Not In (1,2,3,4))
    Return(@DetailReturnCode)
 	  	 
 	 Select 10,0,@UserId,@TransType,@TransNum,@Event_Id,@PU_Id,null,@ED_AltEventNum,@ED_CommentId,
 	  	 null,null,null,null,@Timestamp,@ED_EntryOn,@ED_PPSetupDetailId,@ED_ShipmentId,@ED_OrderId,
 	  	 @ED_OrderLineId,@ED_PPId,@ED_InitialDimX,@ED_InitialDimY,@ED_InitialDimZ,@ED_InitialDimA,
 	  	 @ED_FinalDimX,@ED_FinalDimY,@ED_FinalDimZ,@ED_FinalDimA,
 	  	 @ED_OrientationX,@ED_OrientationY,@ED_OrientationZ,@ED_SignatureId,@ED_ProductDefId
 	  	  	  	 
 	 Return(5) 	  	  	 
