import icons from "../../../../resources/icons";
import { getIcon } from "../../../../utils";

export function gridTaskUpdateToolbarPreparing(
  e,
  t,
  onClickCustomizeView,
  onClickSaveChanges,
  onClickExportToPDF,
  onClickExportToExcel,
  customizeViewListItems
) {
  var columnChooser = e.toolbarOptions.items.find(
    (i) => i.name === "columnChooserButton"
  );

  columnChooser.location = "before";
  columnChooser.options.icon = getIcon(icons.columnChooser);

  return e.toolbarOptions.items.unshift(
    {
      location: "before",
      widget: "dxButton",
      cssClass: "btnSaveChangesVersionMgmt",
      options: {
        disabled: false,
        icon: getIcon(icons.save),
        hint: t("Save Changes"),
        onClick: onClickSaveChanges,
      },
    },
    {
      location: "before",
      widget: "dxDropDownButton",
      cssClass: "btnCustomizeVersionMgmt",
      options: {
        hint: "Customize",
        icon: getIcon(icons.customize),
        keyExpr: "id",
        displayExpr: "text",
        onSelectionChanged: onClickCustomizeView,
        items: customizeViewListItems(),
        dropDownOptions: {
          width: "auto",
        },
      },
    },
    {
      location: "after",
      widget: "dxButton",
      cssClass: "btnExcelExportVersionMgmt",
      options: {
        hint: t("Export to Excel"),
        icon: getIcon(icons.excel),
        onClick: onClickExportToExcel,
      },
    },
    {
      location: "after",
      widget: "dxButton",
      cssClass: "btnPdfExportVersionMgmt",
      options: {
        hint: t("Export to PDF"),
        icon: getIcon(icons.pdf),
        onClick: onClickExportToPDF,
      },
    }
  );
}

export const gridTasksUpdatesColumns = [
  {
    dataField: "Status", // ###
    caption: "Status",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: -1,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "succes_failure", // ###
    caption: "Success/Failure",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 1,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "VarId",
    caption: "Var_Id",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: true,
    visibleIndex: 1,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "DepartmentId",
    caption: "Department_Id",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: false,
    visibleIndex: 2,
    showInColumnChooser: false,
    exportEnable: false,
  },
  {
    dataField: "DepartmentDesc",
    caption: "Area",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 3,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "PLId",
    caption: "Line_Id",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: false,
    visibleIndex: 4,
    showInColumnChooser: false,
    exportEnable: false,
  },
  {
    dataField: "LineDesc",
    caption: "Line",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 5,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "MasterUnitId",
    caption: "MasterUnit_Id",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: false,
    visibleIndex: 6,
    showInColumnChooser: false,
    exportEnable: false,
  },
  {
    dataField: "MasterUnitDesc",
    caption: "Primary Unit",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 7,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "SlaveUnitId",
    caption: "SlaveUnit_Id",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: false,
    visibleIndex: 8,
    showInColumnChooser: false,
    exportEnable: false,
  },
  {
    dataField: "SlaveUnitDesc",
    caption: "Module",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 9,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "ProductionGroupId",
    caption: "ProductionGroup_Id",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: false,
    visibleIndex: 10,
    showInColumnChooser: false,
    exportEnable: false,
  },
  {
    dataField: "ProductionGroupDesc",
    caption: "Group",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 11,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "VarDesc",
    caption: "Task Name",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 12,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "VMId",
    caption: "VMId",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 13,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "TaskLocation",
    caption: "Task Location",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 14,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "TaskId",
    caption: "Task Id",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 15,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "TaskType",
    caption: "Task Type",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 16,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "TaskAction",
    caption: "Task Action",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 17,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Active",
    caption: "Active",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 18,
    showInColumnChooser: true,
    exportEnable: false,
  },
  {
    dataField: "FrequencyType",
    caption: "Frequency",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 19,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Frequency",
    caption: "Period",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 20,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Window",
    caption: "Window",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 21,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "TestTime",
    caption: "Test Time",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 22,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "FixedFrequency",
    caption: "Fixed Frequency",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 23,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "FL1",
    caption: "FL1",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 24,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "FL2",
    caption: "FL2",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 25,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "FL3",
    caption: "FL3",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 26,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "FL4",
    caption: "FL4",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 27,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "LongTaskName",
    caption: "Long Task Name",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 28,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "NbrItems",
    caption: "# Items",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 30,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Duration",
    caption: "Duration",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 31,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "NbrPeople",
    caption: "# People",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 32,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Criteria",
    caption: "Criteria",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 33,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Hazards",
    caption: "Hazards",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 34,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Method",
    caption: "Method",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 35,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "PPE",
    caption: "PPE",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 36,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Tools",
    caption: "Tools",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 37,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "Lubricant",
    caption: "Lubricant",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 38,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "DocumentLinkPath",
    caption: "Document Link Path",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 39,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "DocumentLinkTitle",
    caption: "Document Link Title",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 40,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "QFactorType",
    caption: "Q-Factor Type",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 41,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "PrimaryQFactor",
    caption: "Primary Q-Factor",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 42,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "TaskFreq",
    caption: "Task Frequency",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 43,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "ScheduleScope",
    caption: "Schedule Scope",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 44,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "StartDate",
    caption: "Start Date",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 45,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "LineVersion",
    caption: "Line Version",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 46,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "ModuleFeatureVersion",
    caption: "Module Feature Version",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 47,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "IsHSE",
    caption: "Is HSE?",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 48,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "ShiftOffset",
    caption: "Shift Offset",
    visibility: false,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 49,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "VMLocalId",
    caption: "VMLocalId",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: false,
    visibleIndex: 50,
    showInColumnChooser: false,
    exportEnable: false,
  },
  {
    dataField: "AutoPostpone",
    caption: "AutoPostpone",
    visibility: false,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: true,
    visibleIndex: 51,
    showInColumnChooser: true,
    exportEnable: true,
  },
];

export const getDataSourceComparisionProgress = [
  {
    id: 1,
    Status: "waiting",
    Step: "Raw Data File Upload", // ReadDataFromExcelFile
    Information: "",
  },
  {
    id: 2,
    Status: "waiting",
    Step: "Raw Data File Validation", // ReadandValidateRawDatafile
    Information: "",
  },
  {
    id: 3,
    Status: "waiting",
    Step: "Proficy Data Upload", // ReadProficyData
    Information: "",
  },
  {
    id: 4,
    Status: "waiting",
    Step: "Proficy Plant Model Validation",
    Information: "",
  },
  {
    id: 5,
    Status: "waiting",
    Step: "Data Comparision",
    Information: "",
  },
  {
    id: 6,
    Status: "waiting",
    Step: "Update Comparision Results",
    Information: "",
  },
];

export const gridErrorColumns = [
  {
    dataField: "rowNbr", // ###
    caption: "Row Nbr",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 46,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "columnName", // ###
    caption: "Column Name",
    visibility: true,
    allowEditing: false,
    allowSearch: true,
    allowFiltering: true,
    visibleIndex: 47,
    showInColumnChooser: true,
    exportEnable: true,
  },
  {
    dataField: "errorMessage",
    caption: "Error Message",
    visibility: true,
    allowEditing: false,
    allowSearch: false,
    allowFiltering: true,
    visibleIndex: 1,
    showInColumnChooser: true,
    exportEnable: true,
  },
];

export const gridMasterUnitAssignmentColumns = [
  {
    dataField: "DepartmentDesc",
    caption: "Department",
  },
  {
    dataField: "LineDesc",
    caption: "Line",
  },
  {
    dataField: "MasterUnitDesc",
    caption: "Primary Unit",
  },
  {
    dataField: "SlaveUnitDesc",
    caption: "Module",
  },
  {
    dataField: "FL1",
    caption: "FL1",
  },
  {
    dataField: "FL2",
    caption: "FL2",
  },
  {
    dataField: "FL3",
    caption: "FL3",
  },
];
