CREATE LOGIN [ComXclient]
    WITH PASSWORD = N'ifcvZp$nqLz|kUlg1cosrqvqmsFT7_&#$!~<k+tbcetXEdpd', SID = 0x88B7ECA1D9DA174EB815E8B68768E0AF, DEFAULT_DATABASE = [GBDB], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

