CREATE ROLE [R_MESECIL]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [R_MESECIL] ADD MEMBER [NA\LAB0132eCIL.im];


GO
ALTER ROLE [R_MESECIL] ADD MEMBER [NA\msmesecil.im];


GO
ALTER ROLE [R_MESECIL] ADD MEMBER [INT\eCILNPLQA.im];

