CREATE view SDK_V_PABOMFormulation
as
select
Bill_Of_Material_Formulation.BOM_Formulation_Id as Id,
Bill_Of_Material_Formulation.BOM_Formulation_Desc as BOMFormulation,
Bill_Of_Material_Formulation.BOM_Formulation_Code as BOMFormulationCode,
Bill_Of_Material_Formulation.BOM_Id as BOMId,
BOM.BOM_Desc as BOM,
Bill_Of_Material_Formulation.Comment_Id as CommentId,
Comments.Comment_Text as CommentText,
Bill_Of_Material_Formulation.Effective_Date as EffectiveDate,
Bill_Of_Material_Formulation.Eng_Unit_Id as EngineeringUnitId,
EngUnits.Eng_Unit_Desc as EngineeringUnit,
Bill_Of_Material_Formulation.Expiration_Date as ExpirationDate,
Bill_Of_Material_Formulation.Master_BOM_Formulation_Id as MasterBOMFormulationId,
Master.BOM_Formulation_Desc as MasterBOMFormulation,
Bill_Of_Material_Formulation.Quantity_Precision as QuantityPrecision,
Bill_Of_Material_Formulation.Standard_Quantity as StandardQuantity
From Bill_Of_Material_Formulation
 LEFT JOIN  Bill_Of_Material_Formulation Master on Master.BOM_Formulation_Id =  Bill_Of_Material_Formulation.Master_BOM_Formulation_Id
 JOIN Bill_Of_Material BOM on BOM.BOM_Id = Bill_Of_Material_Formulation.BOM_Id
 JOIN Engineering_Unit EngUnits on EngUnits.Eng_Unit_Id = Bill_Of_Material_Formulation.Eng_Unit_Id
LEFT JOIN Comments Comments on Comments.Comment_Id=Bill_Of_Material_Formulation.Comment_Id
