CREATE view SDK_V_PAAlarmTemplateVariableRuleData
as
select
Alarm_Template_Variable_Rule_Data.ATVRD_Id as Id,
alarm_templates.at_desc as AlarmTemplate,
Alarm_Template_Variable_Rule_Data.at_id as AlarmTemplateId,
alarm_variable_rules.alarm_variable_rule_desc as AlarmVariableRule,
Alarm_Template_Variable_Rule_Data.alarm_variable_rule_id as AlarmVariableRuleId,
Alarm_Template_Variable_Rule_Data.AP_Id as AlarmPriorityId,
AP_Src.AP_Desc as AlarmPriority
from Alarm_Template_Variable_Rule_Data
join Alarm_Templates on Alarm_Templates.AT_Id = Alarm_Template_Variable_Rule_Data.AT_Id
join Alarm_Variable_Rules on Alarm_Variable_Rules.Alarm_Variable_Rule_Id = Alarm_Template_Variable_Rule_Data.Alarm_Variable_Rule_Id
 Left Join Alarm_Priorities AP_Src on AP_Src.AP_Id = Alarm_Template_Variable_Rule_Data.AP_Id 
