CREATE view SDK_V_PABOMFormulationItem
as
select
Bill_Of_Material_Formulation_Item.BOM_Formulation_Item_Id as Id,
Bill_Of_Material_Formulation_Item.Alias as Alias,
Bill_Of_Material_Formulation_Item.BOM_Formulation_Id as BOMFormulationId,
Formulation.BOM_Formulation_Desc as BOMFormulation,
Bill_Of_Material_Formulation_Item.BOM_Formulation_Order as BOMFormulationOrder,
Bill_Of_Material_Formulation_Item.Comment_Id as CommentId,
Comments.Comment_Text as CommentText,
EngUnits.Eng_Unit_Desc as EngineeringUnit,
Bill_Of_Material_Formulation_Item.Eng_Unit_Id as EngineeringUnitId,
Unit_Locations.Location_Desc as UnitLocation,
Bill_Of_Material_Formulation_Item.Location_Id as UnitLocationId,
Bill_Of_Material_Formulation_Item.Lot_Desc as Lot,
Bill_Of_Material_Formulation_Item.Lower_Tolerance as LowerTolerance,
Bill_Of_Material_Formulation_Item.LTolerance_Precision as LowerTolerancePrecision,
Bill_Of_Material_Formulation_Item.Prod_Id as ProductId,
Products.Prod_Code as ProductCode,
Departments_Base.Dept_Desc as Department,
Prod_Lines_Base.Dept_Id as DepartmentId,
Prod_Lines_Base.PL_Desc as ProductionLine,
Prod_Units_Base.PL_Id as ProductionLineId,
Prod_Units_Base.PU_Desc as ProductionUnit,
Bill_Of_Material_Formulation_Item.PU_Id as ProductionUnitId,
Bill_Of_Material_Formulation_Item.Quantity as Quantity,
Bill_Of_Material_Formulation_Item.Quantity_Precision as QuantityPrecision,
Bill_Of_Material_Formulation_Item.Scrap_Factor as ScrapFactor,
Bill_Of_Material_Formulation_Item.Upper_Tolerance as UpperTolerance,
Bill_Of_Material_Formulation_Item.UTolerance_Precision as UpperTolerancePrecision,
Bill_Of_Material_Formulation_Item.Use_Event_Components as UseEventComponents
FROM Bill_Of_Material_Formulation_Item
LEFT
 JOIN Products On Products.Prod_Id = Bill_Of_Material_Formulation_Item.Prod_Id
JOIN Bill_Of_Material_Formulation Formulation On Formulation.BOM_Formulation_Id = Bill_Of_Material_Formulation_Item.BOM_Formulation_Id
JOIN Engineering_Unit EngUnits on EngUnits.Eng_Unit_Id = Bill_Of_Material_Formulation_Item.Eng_Unit_Id
LEFT
 JOIN Unit_Locations on Unit_Locations.Location_Id = Bill_Of_Material_Formulation_Item.Location_Id
LEFT
 JOIN Prod_Units_Base ON Bill_Of_Material_Formulation_Item.PU_Id = Prod_Units_Base.PU_Id
LEFT
 JOIN Prod_Lines_Base ON Prod_Units_Base.PL_Id = Prod_Lines_Base.PL_Id AND Prod_Units_Base.PU_Id > 0
LEFT
 JOIN Departments_Base ON Prod_Lines_Base.Dept_Id = Departments_Base.Dept_Id AND Prod_Lines_Base.PL_Id > 0
LEFT JOIN Comments Comments on Comments.Comment_Id=Bill_Of_Material_Formulation_Item.Comment_Id
