CREATE view SDK_V_PABOMSubstitution
as
select
Bill_Of_Material_Substitution.BOM_Substitution_Id as Id,
Bill_Of_Material_Substitution.BOM_Formulation_Item_Id as BOMFormulationItemId,
Bill_Of_Material_Substitution.BOM_Substitution_Order as BOMSubstitutionOrder,
Bill_Of_Material_Substitution.Conversion_Factor as ConversionFactor,
Engineering_Unit.Eng_Unit_Desc as EngineeringUnit,
Bill_Of_Material_Substitution.Eng_Unit_Id as EngineeringUnitId,
Products.Prod_Code as ProductCode,
Bill_Of_Material_Substitution.Prod_Id as ProductId
FROM Bill_Of_Material_Substitution 
LEFT
 JOIN Products On Products.Prod_Id = Bill_Of_Material_Substitution.Prod_Id
JOIN Bill_Of_Material_Formulation_Item Item On Item.BOM_Formulation_Item_Id = Bill_Of_Material_Substitution.BOM_Formulation_Item_Id
JOIN Engineering_Unit on Engineering_Unit.Eng_Unit_Id = Bill_Of_Material_Substitution.Eng_Unit_Id
