CREATE view SDK_V_PACustomerOrderLine
as
select
Customer_Order_Line_Items.Order_Line_Id as Id,
Customer.Customer_Code as CustomerCode,
Customer_Orders.Plant_Order_Number as PlantOrderNumber,
Customer_Order_Line_Items.Is_Active as IsActive,
Customer_Order_Line_Items.Line_Item_Number as LineItemNumber,
Customer_Order_Line_Items.Ordered_Quantity as OrderedQuantity,
Customer_Order_Line_Items.Ordered_UOM as OrderedUnitOfMeasure,
Customer_Order_Line_Items.Dimension_X as DimensionX,
Customer_Order_Line_Items.Dimension_Y as DimensionY,
Customer_Order_Line_Items.Dimension_Z as DimensionZ,
Customer_Order_Line_Items.Dimension_A as DimensionA,
Customer_Order_Line_Items.Dimension_X_Tolerance as DimensionXTolerance,
Customer_Order_Line_Items.Dimension_Y_Tolerance as DimensionYTolerance,
Customer_Order_Line_Items.Dimension_Z_Tolerance as DimensionZTolerance,
Customer_Order_Line_Items.Dimension_A_Tolerance as DimensionATolerance,
consignee.Customer_Code as ConsigneeCode,
shipto.Customer_Code as ShipToCustomerCode,
enduser.Customer_Code as EndCustomerCode,
Customer_Order_Line_Items.COA_Date as COADate,
Products.Prod_Code as ProductCode,
Customer_Order_Line_Items.Order_Line_General_1 as OrderLineGeneral1,
Customer_Order_Line_Items.Order_Line_General_2 as OrderLineGeneral2,
Customer_Order_Line_Items.Order_Line_General_3 as OrderLineGeneral3,
Customer_Order_Line_Items.Order_Line_General_4 as OrderLineGeneral4,
Customer_Order_Line_Items.Order_Line_General_5 as OrderLineGeneral5,
Customer_Order_Line_Items.Order_Id as CustomerOrderId,
Customer_Order_Line_Items.Comment_Id as CommentId,
Customer_Order_Line_Items.Extended_Info as ExtendedInfo,
Customer_Order_Line_Items.Complete_Date as CompleteDate,
Customer_Order_Line_Items.Consignee_Id as ConsigneeId,
Customer_Orders.Customer_Id as CustomerId,
Customer_Order_Line_Items.EndUser_Id as EndCustomerId,
Customer_Order_Line_Items.ShipTo_Id as ShipToCustomerId,
Customer_Order_Line_Items.Prod_Id as ProductId,
Comments.Comment_Text as CommentText,
Customer_Orders.Customer_Order_Number as CustomerOrderNumber,
Customer_Orders.Corporate_Order_Number as CorporateOrderNumber
FROM Customer_Orders
 INNER JOIN Customer_Order_Line_Items ON Customer_Order_Line_Items.Order_Id = Customer_Orders.Order_Id 
 INNER JOIN Products ON products.Prod_Id = Customer_Order_Line_Items.Prod_Id
 INNER JOIN Customer ON Customer.Customer_Id = Customer_Orders.Customer_Id 
 LEFT JOIN Customer consignee ON consignee.Customer_Id = Customer_Order_Line_Items.Consignee_Id 
 LEFT JOIN Customer shipto ON shipto.Customer_Id = Customer_Order_Line_Items.ShipTo_Id 
 LEFT JOIN Customer enduser  ON enduser.Customer_Id = Customer_Order_Line_Items.EndUser_Id
LEFT JOIN Comments Comments on Comments.Comment_Id=customer_order_line_items.Comment_Id
