CREATE PROCEDURE [dbo].[Splocal_check_Ready_PO_values]
@OUTPUTVALUE INT NULL OUTPUT, @pu_id INT NULL, @INTBATCHIDVarID INT NULL, @INTPROCESSORDERVARID INT NULL, @INTMATERIALCODEVarID INT NULL, @INTPLANNEDQTYVARID INT NULL, @INTEXPIRATIONDATEVARID INT NULL, @CheckReadyvarid INT NULL, @Eventid INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


