CREATE FUNCTION [dbo].[fnLocal_Bets_RawData]
(@p_intConstraintPUId INT NULL, @p_vchStartDateTime VARCHAR (25) NULL, @p_vchEndDateTime VARCHAR (25) NULL, @p_intSplitRecords INT NULL, @p_intIncludeShift INT NULL)
RETURNS 
    @GeneratedTableName TABLE (
        [RcdIdx]                  INT           IDENTITY (1, 1) NOT NULL,
        [PLId]                    INT           NULL,
        [Shift]                   VARCHAR (50)  NULL,
        [Team]                    VARCHAR (50)  NULL,
        [BatchId]                 INT           NULL,
        [BatchPUId]               INT           NULL,
        [BatchNumber]             VARCHAR (100) NULL,
        [BatchStart]              VARCHAR (25)  NULL,
        [BatchEnd]                VARCHAR (25)  NULL,
        [BatchConstraintPUId]     INT           NULL,
        [BatchStatusId]           INT           NULL,
        [UPID]                    INT           NULL,
        [UPPUId]                  INT           NULL,
        [UPNumber]                VARCHAR (100) NULL,
        [UPStart]                 VARCHAR (25)  NULL,
        [UPEnd]                   VARCHAR (25)  NULL,
        [UPStartForRpt]           VARCHAR (25)  NULL,
        [UPEndForRpt]             VARCHAR (25)  NULL,
        [UPStatusId]              INT           NULL,
        [UPProdId]                INT           NULL,
        [UPPSProdId]              INT           NULL,
        [UPAppliedProdId]         INT           NULL,
        [OperationId]             INT           NULL,
        [OperationNumber]         VARCHAR (250) NULL,
        [PhaseId]                 INT           NULL,
        [PhaseNumber]             VARCHAR (250) NULL,
        [PhaseStart]              VARCHAR (25)  NULL,
        [PhaseEnd]                VARCHAR (25)  NULL,
        [BETSId]                  INT           NULL,
        [BETSType]                VARCHAR (10)  NULL,
        [BETSNumber]              VARCHAR (250) NULL,
        [BETSStart]               VARCHAR (25)  NULL,
        [BETSEnd]                 VARCHAR (25)  NULL,
        [BETSStartForRpt]         VARCHAR (25)  NULL,
        [BETSEndForRpt]           VARCHAR (25)  NULL,
        [BETSDurationInSec]       INT           NULL,
        [BETSDurationInSecForRpt] INT           NULL,
        [BETSModifiedOn]          VARCHAR (25)  NULL,
        [BETSUserId]              INT           NULL,
        [BETSCount]               INT           NULL,
        [BETSEventSubTypeId]      INT           NULL,
        [BETSCommentId]           INT           NULL,
        [OffsetFromMidnightinSec] INT           NULL,
        [ProductionDay]           VARCHAR (25)  NULL,
        [CauseTreeId]             INT           NULL,
        [Cause1Id]                INT           NULL,
        [Cause2Id]                INT           NULL,
        [Cause3Id]                INT           NULL,
        [Cause4Id]                INT           NULL,
        [CauseCommentId]          INT           NULL,
        [CauseTreeNodeId]         INT           NULL,
        [ActionTreeId]            INT           NULL,
        [Action1Id]               INT           NULL,
        [Action2Id]               INT           NULL,
        [Action3Id]               INT           NULL,
        [Action4Id]               INT           NULL,
        [ActionCommentID]         INT           NULL,
        [ActionTreeNodeId]        INT           NULL,
        [ResearchOpen]            VARCHAR (25)  NULL,
        [ResearchClose]           VARCHAR (25)  NULL,
        [ResearchStatusID]        INT           NULL,
        [ResearchUserId]          INT           NULL,
        [ResearchCommentID]       INT           NULL,
        [EventSplitFactor]        FLOAT (53)    NULL,
        [EventSplitFlag]          INT           DEFAULT ((0)) NULL,
        [EventSplitShiftFlag]     INT           DEFAULT ((0)) NULL,
        [OverlapFlag]             INT           DEFAULT ((0)) NULL,
        [OverlapSequence]         INT           DEFAULT ((0)) NULL,
        [OverlapRcdFlag]          INT           DEFAULT ((0)) NULL,
        [ErrorCode]               INT           NULL,
        [Error]                   VARCHAR (150) NULL)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

