CREATE FUNCTION [dbo].[fnLocal_BETS_BatchPhaseData]
(@p_intPLId INT NULL, @p_vchStartDateTime VARCHAR (25) NULL, @p_vchEndDateTime VARCHAR (25) NULL, @p_vchRetrievePhaseData BIT NULL, @p_vchBatchID INT NULL, @p_intConstraintPUId INT NULL, @p_vchSpare2 BIT NULL, @p_vchSpare3 BIT NULL)
RETURNS 
    @GeneratedTableName TABLE (
        [RcdIdx]                   INT           IDENTITY (1, 1) NOT NULL,
        [PLId]                     INT           NULL,
        [PLDesc]                   VARCHAR (50)  NULL,
        [BatchId]                  INT           NULL,
        [BatchPUId]                INT           NULL,
        [BatchPUDesc]              VARCHAR (50)  NULL,
        [BatchNumber]              VARCHAR (50)  NULL,
        [BatchSeq]                 INT           NULL,
        [BatchStart]               VARCHAR (25)  NULL,
        [BatchEnd]                 VARCHAR (25)  NULL,
        [BatchDurationInSec]       FLOAT (53)    NULL,
        [BatchConstraintPUId]      INT           NULL,
        [BatchConstraintPUIdDesc]  VARCHAR (50)  NULL,
        [BatchStateVarId]          INT           NULL,
        [BatchStateDesc]           VARCHAR (50)  NULL,
        [BatchVolumeVarId]         INT           NULL,
        [BatchVolumeInKg]          FLOAT (53)    NULL,
        [BatchBCTTargetVarId]      INT           NULL,
        [BatchBCTTargetInSec]      FLOAT (53)    NULL,
        [BatchBCTIdealVarId]       INT           NULL,
        [BatchBCTIdealInSec]       FLOAT (53)    NULL,
        [BatchBCTActualVarId]      INT           NULL,
        [BatchBCTActualInSec]      FLOAT (53)    NULL,
        [BatchUpTimeVarId]         INT           NULL,
        [BatchUpTimeInSec]         FLOAT (53)    NULL,
        [BatchTargetSizeVarId]     INT           NULL,
        [BatchTargetSizeInKg]      FLOAT (53)    NULL,
        [BatchRUVarId]             INT           NULL,
        [BatchRU]                  FLOAT (53)    NULL,
        [BatchEffVarId]            INT           NULL,
        [BatchEff]                 FLOAT (53)    NULL,
        [BatchStatVarId]           INT           NULL,
        [BatchStat]                FLOAT (53)    NULL,
        [BatchTargetBCRInKgPerMin] FLOAT (53)    NULL,
        [BatchYield]               FLOAT (53)    NULL,
        [BatchUPTimeBatchEff]      FLOAT (53)    NULL,
        [BatchUpTimeBatchRU]       FLOAT (53)    NULL,
        [BatchUpTimeBatchYield]    FLOAT (53)    NULL,
        [UPID]                     INT           NULL,
        [UPPUId]                   INT           NULL,
        [UPPUDesc]                 VARCHAR (50)  NULL,
        [UPNumber]                 VARCHAR (100) NULL,
        [UPStart]                  VARCHAR (25)  NULL,
        [UPEnd]                    VARCHAR (25)  NULL,
        [UPDurationInSec]          FLOAT (53)    NULL,
        [UPProdId]                 INT           NULL,
        [UPProdCode]               VARCHAR (50)  NULL,
        [UPProdDesc]               VARCHAR (50)  NULL,
        [UPPSProdId]               INT           NULL,
        [UPAppliedProdId]          INT           NULL,
        [OperationId]              INT           NULL,
        [OperationNumber]          VARCHAR (250) NULL,
        [OperationName]            VARCHAR (50)  NULL,
        [OperationInstance]        VARCHAR (50)  NULL,
        [PhaseId]                  INT           NULL,
        [PhaseNumber]              VARCHAR (250) NULL,
        [PhaseName]                VARCHAR (50)  NULL,
        [PhaseInstance]            VARCHAR (50)  NULL,
        [PhaseStart]               VARCHAR (25)  NULL,
        [PhaseEnd]                 VARCHAR (25)  NULL,
        [PhaseDurationInSec]       FLOAT (53)    NULL,
        [PhasePCTTargetVarId]      INT           NULL,
        [PhasePCTTargetInSec]      FLOAT (53)    NULL,
        [PhasePCTIdealVarId]       INT           NULL,
        [PhasePCTIdealInSec]       FLOAT (53)    NULL,
        [BatchShift]               VARCHAR (50)  NULL,
        [BatchTeam]                VARCHAR (50)  NULL,
        [ErrorCode]                INT           NULL,
        [Error]                    VARCHAR (150) NULL)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

