CREATE FUNCTION [dbo].[fnLocal_BETS_BatchData]
(@p_intConstraintPUId INT NULL, @p_vchStartDateTime VARCHAR (25) NULL, @p_vchEndDateTime VARCHAR (25) NULL, @p_intSplitRecords INT NULL, @p_intIncludeShift INT NULL)
RETURNS 
    @GeneratedTableName TABLE (
        [RcdIdx]                   INT           IDENTITY (1, 1) NOT NULL,
        [PLId]                     INT           NULL,
        [PLDesc]                   VARCHAR (50)  NULL,
        [BatchPUID]                INT           NULL,
        [BatchPUDesc]              VARCHAR (50)  NULL,
        [BatchShift]               VARCHAR (50)  NULL,
        [BatchTeam]                VARCHAR (50)  NULL,
        [BatchID]                  INT           NULL,
        [BatchNumber]              VARCHAR (50)  NULL,
        [BatchSeq]                 VARCHAR (50)  NULL,
        [BatchConstraintPUId]      INT           NULL,
        [BatchConstraintPUIdDesc]  VARCHAR (50)  NULL,
        [BatchStateVarId]          INT           NULL,
        [BatchStateDesc]           VARCHAR (50)  NULL,
        [BatchVolumeVarId]         INT           NULL,
        [BatchVolumeInKg]          FLOAT (53)    NULL,
        [BatchBCTTargetVarId]      INT           NULL,
        [BatchBCTTargetInSec]      FLOAT (53)    NULL,
        [BatchBCTIdealVarId]       INT           NULL,
        [BatchBCTIdealInSec]       FLOAT (53)    NULL,
        [BatchBCTActualVarId]      INT           NULL,
        [BatchBCTActualInSec]      FLOAT (53)    NULL,
        [BatchUpTimeVarId]         INT           NULL,
        [BatchUpTimeInSec]         FLOAT (53)    NULL,
        [BatchTargetSizeVarId]     INT           NULL,
        [BatchTargetSizeInKg]      FLOAT (53)    NULL,
        [BatchRUVarId]             INT           NULL,
        [BatchRU]                  FLOAT (53)    NULL,
        [BatchEffVarId]            INT           NULL,
        [BatchEff]                 FLOAT (53)    NULL,
        [BatchStatVarId]           INT           NULL,
        [BatchStat]                FLOAT (53)    NULL,
        [BatchTargetBCRInKgPerMin] FLOAT (53)    NULL,
        [BatchYield]               FLOAT (53)    NULL,
        [BatchUPTimeBatchEff]      FLOAT (53)    NULL,
        [BatchUpTimeBatchRU]       FLOAT (53)    NULL,
        [BatchUpTimeBatchYield]    FLOAT (53)    NULL,
        [BatchDurationInSec]       FLOAT (53)    NULL,
        [BatchCount]               INT           NULL,
        [UPId]                     INT           NULL,
        [UPNumber]                 VARCHAR (50)  NULL,
        [UPPUID]                   INT           NULL,
        [UPPUDesc]                 VARCHAR (50)  NULL,
        [UPProdId]                 INT           NULL,
        [UPProdCode]               VARCHAR (50)  NULL,
        [UPProdDesc]               VARCHAR (50)  NULL,
        [UPProdFilterSpecId]       INT           NULL,
        [UPProdCharId]             INT           NULL,
        [UPProdFilterSpecValue]    INT           DEFAULT ((0)) NULL,
        [UPStart]                  DATETIME      NULL,
        [UPEnd]                    DATETIME      NULL,
        [UPStartForRpt]            DATETIME      NULL,
        [UPEndForRpt]              DATETIME      NULL,
        [BatchSplitFactor]         FLOAT (53)    NULL,
        [BatchSplitFlag]           INT           NULL,
        [BatchSplitShiftFlag]      INT           DEFAULT ((0)) NULL,
        [OverlapFlag]              INT           DEFAULT ((0)) NULL,
        [OverlapSequence]          INT           DEFAULT ((0)) NULL,
        [OverlapRcdFlag]           INT           DEFAULT ((0)) NULL,
        [ErrorCode]                INT           NULL,
        [Error]                    VARCHAR (150) NULL)
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END

