CREATE TABLE [dbo].[Trans_Metric_Properties] (
    [AS_Id]            INT                   NOT NULL,
    [Char_Id]          INT                   NOT NULL,
    [Effective_Date]   DATETIME              NULL,
    [Esignature_Level] INT                   NULL,
    [L_Control]        VARCHAR (25)          NULL,
    [L_Entry]          [dbo].[Varchar_Value] NULL,
    [L_Reject]         [dbo].[Varchar_Value] NULL,
    [L_User]           [dbo].[Varchar_Value] NULL,
    [L_Warning]        [dbo].[Varchar_Value] NULL,
    [Spec_Id]          INT                   NOT NULL,
    [T_Control]        VARCHAR (25)          NULL,
    [Target]           [dbo].[Varchar_Value] NULL,
    [Trans_Id]         INT                   NOT NULL,
    [U_Control]        VARCHAR (25)          NULL,
    [U_Entry]          [dbo].[Varchar_Value] NULL,
    [U_Reject]         [dbo].[Varchar_Value] NULL,
    [U_User]           [dbo].[Varchar_Value] NULL,
    [U_Warning]        [dbo].[Varchar_Value] NULL,
    CONSTRAINT [TransMetProps_PK_TransSpecCharAsId] PRIMARY KEY CLUSTERED ([Trans_Id] ASC, [Spec_Id] ASC, [Char_Id] ASC, [AS_Id] ASC),
    CONSTRAINT [TransMetProps_FK_CharId] FOREIGN KEY ([Char_Id]) REFERENCES [dbo].[Characteristics] ([Char_Id]),
    CONSTRAINT [TransMetProps_FK_SpecId] FOREIGN KEY ([Spec_Id]) REFERENCES [dbo].[Specifications] ([Spec_Id]),
    CONSTRAINT [TransMetProps_FK_TransId] FOREIGN KEY ([Trans_Id]) REFERENCES [dbo].[Transactions] ([Trans_Id])
);

