CREATE PROCEDURE [dbo].[spLocal_PG_Cmn_VariableEdit]
@op_ErrorGUID UNIQUEIDENTIFIER NULL OUTPUT, @op_ValidationCode INT NULL OUTPUT, @op_ValidationMessage VARCHAR (MAX) NULL OUTPUT, @p_DebugFlag BIT NULL, @op_VarId INT NULL OUTPUT, @p_VarDesc [dbo].[Varchar_Desc] NULL, @p_PUId INT NULL, @p_PUGId INT NULL, @p_PUGOrder INT NULL, @p_DataTypeId INT NULL, @p_VarPrecision [dbo].[Tinyint_Precision] NULL, @p_SamplingInterval [dbo].[Smallint_Offset] NULL, @p_SamplingOffset [dbo].[Smallint_Offset] NULL, @p_SamplingTypeId TINYINT NULL, @p_EngUnits [dbo].[Varchar_Eng_Units] NULL, @p_DSId INT NULL, @p_EventTypeId TINYINT NULL, @p_UnitReject BIT NULL, @p_UnitSummarize BIT NULL, @p_VarReject BIT NULL, @p_Rank [dbo].[Smallint_Pct] NULL, @p_InputTag VARCHAR (255) NULL, @p_OutputTag VARCHAR (255) NULL, @p_DQTag VARCHAR (255) NULL, @p_UELTag VARCHAR (255) NULL, @p_URLTag VARCHAR (255) NULL, @p_UWLTag VARCHAR (255) NULL, @p_UULTag VARCHAR (255) NULL, @p_TargetTag VARCHAR (255) NULL, @p_LULTag VARCHAR (255) NULL, @p_LWLTag VARCHAR (255) NULL, @p_LRLTag VARCHAR (255) NULL, @p_LELTag VARCHAR (255) NULL, @p_TotFactor REAL NULL, @p_GroupId INT NULL, @p_SpecId INT NULL, @p_SAId TINYINT NULL, @p_Repeating BIT NULL, @p_RepeatBacktime INT NULL, @p_SamplingWindow INT NULL, @p_ShouldArchive BIT NULL, @p_ExtendedInfo VARCHAR (255) NULL, @p_UserDefined1 VARCHAR (255) NULL, @p_UserDefined2 VARCHAR (255) NULL, @p_UserDefined3 VARCHAR (255) NULL, @p_TFReset TINYINT NULL, @p_ForceSign TINYINT NULL, @p_TestName VARCHAR (50) NULL, @p_ExtendedTestFreqId INT NULL, @p_ArrayStatOnly BIT NULL, @p_CTId INT NULL, @p_CV VARCHAR (50) NULL, @p_MaxRPM FLOAT (53) NULL, @p_ResetValue FLOAT (53) NULL, @p_IsConformanceVariable BIT NULL, @p_EsignatureLevel INT NULL, @p_EventSubtypeId INT NULL, @p_EventDimension TINYINT NULL, @p_PEIId INT NULL, @p_SPCCalculationTypeId INT NULL, @p_SPCVariableTypeId INT NULL, @p_InputTag2 VARCHAR (255) NULL, @p_SamplingReferenceVarId INT NULL, @p_StringSpecSetting TINYINT NULL, @p_WriteGroupDSId INT NULL, @p_CPKSubGroupSize INT NULL, @p_ReadLagTime INT NULL, @p_ReloadFlag INT NULL, @p_EventLookup INT NULL, @p_Debug INT NULL, @p_IgnoreEventStatus INT NULL, @p_UserId INT NULL, @p_TransactionType INT NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


