CREATE PROCEDURE [dbo].[splocal_GMP_FireEvents]
@OutputValue VARCHAR (25) NULL OUTPUT, @Var_id INT NULL, @TimeStamp DATETIME NULL, @Varid_TC INT NULL, @EI_NAME VARCHAR (25) NULL, @EI_NAME2 VARCHAR (30) NULL, @EI_TIME VARCHAR (25) NULL, @EI_VARID VARCHAR (25) NULL, @EI_ATT VARCHAR (25) NULL, @EI_FAIL VARCHAR (30) NULL, @EI_Type VARCHAR (30) NULL
WITH ENCRYPTION
AS
BEGIN
--The script body was encrypted and cannot be reproduced here.
    RETURN
END


