CREATE TABLE [dbo].[Color_Scheme] (
    [CS_Id]               INT                  IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Available_BG]        INT                  NOT NULL,
    [Canceled_BG]         INT                  NOT NULL,
    [Column_Header_BG]    INT                  NOT NULL,
    [CS_Desc]             [dbo].[Varchar_Desc] NOT NULL,
    [Entry_FG]            INT                  NOT NULL,
    [Gray_Area]           INT                  NOT NULL,
    [Grid_Lines]          INT                  NOT NULL,
    [Header_FG]           INT                  NOT NULL,
    [Inactive_Area_BG]    INT                  NOT NULL,
    [No_Data_FG]          INT                  NOT NULL,
    [No_Specification_FG] INT                  NOT NULL,
    [Read_Only_BG]        INT                  NOT NULL,
    [Ready_BG]            INT                  NOT NULL,
    [Reject_FG]           INT                  NOT NULL,
    [Row_Header_BG]       INT                  NOT NULL,
    [Target_FG]           INT                  NOT NULL,
    [Unavailable_BG]      INT                  NOT NULL,
    [User_FG]             INT                  NOT NULL,
    [Warning_FG]          INT                  NOT NULL,
    CONSTRAINT [Color_Scheme_PK_CSId] PRIMARY KEY CLUSTERED ([CS_Id] ASC),
    CONSTRAINT [Color_Scheme_UC_CSDesc] UNIQUE NONCLUSTERED ([CS_Desc] ASC)
);

