CREATE TABLE [dbo].[Dashboard_Templates] (
    [Dashboard_Template_ID]               INT            IDENTITY (1, 1) NOT NULL,
    [BaseTemplate]                        BIT            CONSTRAINT [dashboard_templates_DF_BaseTemplate] DEFAULT ((1)) NOT NULL,
    [dashboard_icon_id]                   INT            NULL,
    [Dashboard_Template_Allow_Minimize]   INT            NOT NULL,
    [Dashboard_Template_Allow_Remove]     INT            NOT NULL,
    [Dashboard_Template_Build]            INT            NOT NULL,
    [Dashboard_Template_Cache_Code]       INT            NOT NULL,
    [Dashboard_Template_Cache_Timeout]    INT            NOT NULL,
    [Dashboard_Template_Column]           INT            NOT NULL,
    [Dashboard_Template_Column_Position]  INT            NOT NULL,
    [Dashboard_Template_Description]      VARCHAR (4000) NULL,
    [Dashboard_Template_Detail_Link]      VARCHAR (500)  NULL,
    [Dashboard_Template_Expanded]         INT            NOT NULL,
    [dashboard_template_fixed_height]     BIT            NOT NULL,
    [dashboard_template_fixed_width]      BIT            NOT NULL,
    [Dashboard_Template_Has_Frame]        INT            NOT NULL,
    [Dashboard_Template_Help_Link]        VARCHAR (500)  NULL,
    [Dashboard_Template_Launch_Type]      INT            NOT NULL,
    [Dashboard_Template_Locked]           BIT            NULL,
    [Dashboard_Template_Name]             VARCHAR (100)  NOT NULL,
    [Dashboard_Template_Preview]          IMAGE          NOT NULL,
    [Dashboard_Template_Preview_Filename] VARCHAR (100)  NOT NULL,
    [Dashboard_Template_Procedure]        VARCHAR (100)  NULL,
    [Dashboard_Template_Size_Unit]        INT            NOT NULL,
    [Dashboard_Template_XSL]              TEXT           NOT NULL,
    [Dashboard_Template_XSL_Filename]     VARCHAR (100)  NOT NULL,
    [Group_Id]                            INT            NULL,
    [Height]                              INT            NULL,
    [type]                                INT            CONSTRAINT [DF_Dashboard_Templates_type] DEFAULT ((1)) NOT NULL,
    [version]                             INT            NULL,
    [Width]                               INT            NULL,
    CONSTRAINT [dashboardTemplate_FK_GroupId] FOREIGN KEY ([Group_Id]) REFERENCES [dbo].[Security_Groups] ([Group_Id])
);

