CREATE TABLE [dbo].[DB_Trans_Types] (
    [DBTT_Id]   TINYINT      IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [DBTT_Desc] VARCHAR (25) NOT NULL,
    CONSTRAINT [PK_DB_Trans_Types_DBTTId] PRIMARY KEY CLUSTERED ([DBTT_Id] ASC)
);

