CREATE TABLE [dbo].[ElectronicSignature] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [Status]                NVARCHAR (255)   NULL,
    [Description]           NVARCHAR (1024)  NULL,
    [VerifierRequired]      BIT              NULL,
    [LastModifiedTime]      DATETIME         NULL,
    [PerformerGroupAddress] NVARCHAR (255)   NULL,
    [PerformerGroupName]    NVARCHAR (255)   NULL,
    [PerformerAddress]      NVARCHAR (255)   NULL,
    [PerformerUserName]     NVARCHAR (255)   NULL,
    [PerformerRealName]     NVARCHAR (255)   NULL,
    [PerformerComment]      NVARCHAR (2048)  NULL,
    [PerformerSigningTime]  DATETIME         NULL,
    [VerifierGroupAddress]  NVARCHAR (255)   NULL,
    [VerifierGroupName]     NVARCHAR (255)   NULL,
    [VerifierAddress]       NVARCHAR (255)   NULL,
    [VerifierUserName]      NVARCHAR (255)   NULL,
    [VerifierRealName]      NVARCHAR (255)   NULL,
    [VerifierComment]       NVARCHAR (2048)  NULL,
    [VerifierSigningTime]   DATETIME         NULL,
    [Version]               BIGINT           NULL,
    [Target]                NVARCHAR (2048)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

