CREATE TABLE [dbo].[eSOP_MOTTaskDefects] (
    [DefectNumber]                  INT              IDENTITY (1, 1) NOT NULL,
    [WorkflowDefinitionId]          VARCHAR (1000)   NULL,
    [TaskInstanceId]                UNIQUEIDENTIFIER NULL,
    [TaskInstanceName]              VARCHAR (100)    NULL,
    [TaskStepInstanceId]            UNIQUEIDENTIFIER NULL,
    [TaskStepInstanceName]          VARCHAR (100)    NULL,
    [Created]                       DATETIME         NULL,
    [DefectType]                    VARCHAR (50)     NULL,
    [DefectName]                    VARCHAR (255)    NULL,
    [ShortDescription]              VARCHAR (500)    NULL,
    [DetailedDescription]           VARCHAR (3000)   NULL,
    [Status]                        VARCHAR (25)     NULL,
    [EquipmentId]                   VARCHAR (1000)   NULL,
    [EquipmentName]                 VARCHAR (255)    NULL,
    [Category]                      VARCHAR (100)    NULL,
    [FoundById]                     VARCHAR (1000)   NULL,
    [FoundByName]                   VARCHAR (60)     NULL,
    [CorrectedById]                 VARCHAR (1000)   NULL,
    [CorrectedByName]               VARCHAR (60)     NULL,
    [CorrectedDate]                 DATETIME         NULL,
    [CorrectedComments]             VARCHAR (3000)   NULL,
    [TargetCorrectionDate]          DATETIME         NULL,
    [ExternalHelpNeeded]            BIT              NULL,
    [ExternalSystemReferenceNumber] INT              NULL,
    [FLNumber]                      VARCHAR (20)     NULL,
    [FixedById]                     VARCHAR (1000)   NULL,
    [FixedByName]                   VARCHAR (60)     NULL,
    CONSTRAINT [PK_Defects] PRIMARY KEY CLUSTERED ([DefectNumber] ASC)
);

