CREATE TABLE [dbo].[Local_tblWFRequestMaterialDebug] (
    [Id]                       INT            IDENTITY (1, 1) NOT NULL,
    [SPID]                     INT            NULL,
    [EntryOn]                  DATETIME       NULL,
    [Message]                  VARCHAR (2000) NULL,
    [PPStatusStr]              VARCHAR (50)   NULL,
    [RMProdGroupDesc]          VARCHAR (25)   NULL,
    [BOMRMStoragePUDesc]       VARCHAR (50)   NULL,
    [BOMRMPreStagingLocation]  VARCHAR (50)   NULL,
    [RMProdCode]               VARCHAR (25)   NULL,
    [RMProdDesc]               VARCHAR (50)   NULL,
    [RMSubProdCode]            VARCHAR (25)   NULL,
    [RMPlannedQty]             FLOAT (53)     NULL,
    [RMConsumedQty]            FLOAT (53)     NULL,
    [RMOpenRequestUOMQty]      FLOAT (53)     NULL,
    [RMOpenRequestPalletCnt]   INT            NULL,
    [RMPreStagingUOMQty]       FLOAT (53)     NULL,
    [RMPreStagingPalletCnt]    INT            NULL,
    [RMPreStagingUOMQtySub]    FLOAT (53)     NULL,
    [RMPreStagingPalletCntSub] INT            NULL,
    [RMStagingUOMQty]          FLOAT (53)     NULL,
    [RMStagingPalletCnt]       INT            NULL,
    [RMStagingUOMQtySub]       FLOAT (53)     NULL,
    [RMStagingPalletCntSub]    INT            NULL,
    [RMStagingCapacityPallet]  INT            NULL,
    [RMUOMQTYTotal]            FLOAT (53)     NULL,
    [RMPalletCntTotal]         INT            NULL,
    [RMThresholdCapacity]      INT            NULL,
    [RMNeededUOMQty]           FLOAT (53)     NULL,
    [RMNeededPalletCnt]        INT            NULL,
    [RMRequestUOMQty]          INT            NULL,
    [RMRequestPalletCnt]       INT            NULL,
    [RMUOMPerPallet]           INT            NULL,
    [RMEngUnitDesc]            VARCHAR (25)   NULL,
    [FlgNewToInitiateOrder]    BIT            NULL,
    [FlgCheckedIn]             BIT            NULL,
    [FlgRTCISManaged]          BIT            NULL,
    [TOLOCATN]                 VARCHAR (50)   NULL
);

