CREATE TABLE [dbo].[Local_E2P_Global_Products_Metrics] (
    [ProductMetricId]        INT           IDENTITY (1, 1) NOT NULL,
    [ProductId]              INT           NOT NULL,
    [AlternateUoM]           VARCHAR (255) NULL,
    [OriginalUoMSystem]      VARCHAR (255) NOT NULL,
    [Numerator]              INT           NOT NULL,
    [Denominator]            INT           NOT NULL,
    [Gtin]                   VARCHAR (255) NULL,
    [LengthMetric]           VARCHAR (25)  NOT NULL,
    [LengthMetricUoM]        VARCHAR (255) NULL,
    [WidthMetric]            VARCHAR (25)  NOT NULL,
    [WidthMetricUoM]         VARCHAR (255) NULL,
    [HeightMetric]           VARCHAR (25)  NOT NULL,
    [HeightMetricUoM]        VARCHAR (255) NULL,
    [VolumeMetric]           VARCHAR (25)  NOT NULL,
    [VolumeMetricUoM]        VARCHAR (255) NULL,
    [GrossWeightMetric]      VARCHAR (25)  NOT NULL,
    [GrossWeightMetricUoM]   VARCHAR (255) NULL,
    [LengthImperial]         VARCHAR (25)  NOT NULL,
    [LengthImperialUoM]      VARCHAR (255) NULL,
    [WidthImperial]          VARCHAR (25)  NOT NULL,
    [WidthImperialUoM]       VARCHAR (255) NULL,
    [HeightImperial]         VARCHAR (25)  NOT NULL,
    [HeightImperialUoM]      VARCHAR (255) NULL,
    [VolumeImperial]         VARCHAR (25)  NOT NULL,
    [VolumeImperialUoM]      VARCHAR (255) NULL,
    [GrossWeightImperial]    VARCHAR (25)  NOT NULL,
    [GrossWeightImperialUoM] VARCHAR (255) NULL,
    CONSTRAINT [LocalE2PGlobalProductsMetrics_PK_ProductMetricId] PRIMARY KEY CLUSTERED ([ProductMetricId] ASC),
    CONSTRAINT [FK_Local_E2P_Global_Products_Metrics_Local_E2P_Global_Products] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Local_E2P_Global_Products] ([ProductId])
);

