CREATE TABLE [dbo].[LOCAL_PE_HEALTH_LOGTYPEATTRIBUTE] (
    [LogTypeAttribute_Id] INT          IDENTITY (1, 1) NOT NULL,
    [LogType_Id]          INT          NOT NULL,
    [LogAttribute_Id]     INT          NOT NULL,
    [Field]               VARCHAR (50) NULL,
    CONSTRAINT [PK_LogTypeAttribute_Id] PRIMARY KEY CLUSTERED ([LogTypeAttribute_Id] ASC),
    CONSTRAINT [FK_HEALTH_LOGTYPEATTRIBUTE_HEALTH_LOGATTRIBUTE] FOREIGN KEY ([LogAttribute_Id]) REFERENCES [dbo].[LOCAL_PE_HEALTH_LOGATTRIBUTE] ([LogAttribute_Id]),
    CONSTRAINT [FK_HEALTH_LOGTYPEATTRIBUTE_HEALTH_LOGTYPE] FOREIGN KEY ([LogType_Id]) REFERENCES [dbo].[LOCAL_PE_HEALTH_LOGTYPE] ([LogType_Id])
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210114-151437]
    ON [dbo].[LOCAL_PE_HEALTH_LOGTYPEATTRIBUTE]([LogTypeAttribute_Id] ASC, [LogType_Id] ASC, [LogAttribute_Id] ASC);

