CREATE TABLE [dbo].[Local_MPWS_GENL_Transactions] (
    [Id]              INT            IDENTITY (1, 1) NOT NULL,
    [TransactionName] VARCHAR (255)  NULL,
    [StationName]     VARCHAR (255)  NULL,
    [UserName]        VARCHAR (255)  NULL,
    [InsertedDate]    DATETIME       CONSTRAINT [DF_Local_MPWS_GENL_Transaction_InsertedDate] DEFAULT (getdate()) NULL,
    [ProcessedDate]   DATETIME       NULL,
    [ErrorCode]       INT            CONSTRAINT [DF_Local_MPWS_GENL_Transaction_ErrorCode] DEFAULT ((0)) NULL,
    [Errormessage]    VARCHAR (1024) NULL,
    [Field01]         VARCHAR (255)  NULL,
    [Field02]         VARCHAR (255)  NULL,
    [Field03]         VARCHAR (255)  NULL,
    [Field04]         VARCHAR (255)  NULL,
    [Field05]         VARCHAR (255)  NULL,
    [Field06]         VARCHAR (255)  NULL,
    [Field07]         VARCHAR (255)  NULL,
    [Field08]         VARCHAR (255)  NULL,
    [Field09]         VARCHAR (255)  NULL,
    [Field10]         VARCHAR (255)  NULL,
    [Field11]         VARCHAR (255)  NULL,
    [Field12]         VARCHAR (255)  NULL,
    [Field13]         VARCHAR (255)  NULL,
    [Field14]         VARCHAR (255)  NULL,
    [Field15]         VARCHAR (255)  NULL,
    [Field16]         VARCHAR (255)  NULL,
    [Field17]         VARCHAR (255)  NULL,
    [Field18]         VARCHAR (255)  NULL,
    [Field19]         VARCHAR (255)  NULL,
    [Field20]         VARCHAR (255)  NULL,
    [OutField01]      VARCHAR (255)  NULL,
    [OutField02]      VARCHAR (255)  NULL,
    [OutField03]      VARCHAR (255)  NULL,
    [OutField04]      VARCHAR (255)  NULL,
    [OutField05]      VARCHAR (255)  NULL,
    CONSTRAINT [PK_Local_MPWS_GENL_Transactions] PRIMARY KEY CLUSTERED ([Id] ASC)
);

