CREATE TABLE [dbo].[Local_INT_GHS_MATERIAL_SAFETY_DATA] (
    [Record_Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [GCAS_Number]                    NVARCHAR (25)   NOT NULL,
    [Signal_Word]                    NVARCHAR (25)   NULL,
    [Corrosion]                      CHAR (1)        NULL,
    [Environment]                    CHAR (1)        NULL,
    [Exclamation_Mark]               CHAR (1)        NULL,
    [Exploding_Bomb]                 CHAR (1)        NULL,
    [Flame]                          CHAR (1)        NULL,
    [Flame_Over_Circle]              CHAR (1)        NULL,
    [Gas_Cylinder]                   CHAR (1)        NULL,
    [Health_Hazard]                  CHAR (1)        NULL,
    [Skulls_and_Crossbones]          CHAR (1)        NULL,
    [Type]                           NVARCHAR (25)   NULL,
    [Document_Id]                    NVARCHAR (25)   NULL,
    [File_Name]                      NVARCHAR (25)   NULL,
    [Common_Name]                    NVARCHAR (50)   NOT NULL,
    [Manufacturer]                   NVARCHAR (255)  NULL,
    [Revision_Date]                  DATETIME        NOT NULL,
    [Language]                       NVARCHAR (50)   NULL,
    [SDS_Format]                     NVARCHAR (25)   NULL,
    [Site_Name]                      NVARCHAR (50)   NULL,
    [SDS_State]                      NVARCHAR (25)   NULL,
    [PrecautionStatement_General]    NVARCHAR (4000) NULL,
    [PrecautionStatement_Prevention] NVARCHAR (4000) NULL,
    [PrecautionStatement_Response]   NVARCHAR (4000) NULL,
    [PrecautionStatement_Storage]    NVARCHAR (4000) NULL,
    [PrecautionStatement_Disposal]   NVARCHAR (4000) NULL,
    [HazardStatement_Physical]       NVARCHAR (4000) NULL,
    [HazardStatement_Health]         NVARCHAR (4000) NULL,
    [HazardStatement_Environmental]  NVARCHAR (4000) NULL,
    [SDS1]                           NVARCHAR (255)  NULL,
    [SDS2]                           NVARCHAR (255)  NULL,
    [SDS3]                           NVARCHAR (255)  NULL,
    [SDS4]                           NVARCHAR (255)  NULL,
    [SDS5]                           NVARCHAR (255)  NULL,
    [Record_Processed_DateTime]      DATETIME        NULL,
    [Processed_Result]               INT             NOT NULL,
    [Error_Message]                  NVARCHAR (4000) NULL,
    CONSTRAINT [Local_INT_GHS_MATERIAL_SAFETY_DATA_PK_Record_Id] PRIMARY KEY NONCLUSTERED ([Record_Id] ASC)
);

