CREATE TABLE [dbo].[Local_E2P_PerfChars] (
    [PerfCharId]             INT            IDENTITY (1, 1) NOT NULL,
    [Status]                 VARCHAR (50)   NULL,
    [FPPId]                  INT            NOT NULL,
    [ComponentId]            INT            NULL,
    [TestMethodName]         VARCHAR (50)   NULL,
    [Characteristic]         VARCHAR (255)  NOT NULL,
    [CharacteristicSpecific] VARCHAR (255)  NULL,
    [ReportType]             VARCHAR (50)   NOT NULL,
    [LowerRoutine]           VARCHAR (25)   NULL,
    [LowerLimit]             VARCHAR (25)   NULL,
    [LowerTarget]            VARCHAR (25)   NULL,
    [Target]                 VARCHAR (25)   NULL,
    [UpperTarget]            VARCHAR (25)   NULL,
    [UpperLimit]             VARCHAR (25)   NULL,
    [UpperRoutine]           VARCHAR (25)   NULL,
    [ReleaseCriteria]        VARCHAR (4000) NULL,
    [TestMethodSpecifics]    VARCHAR (255)  NULL,
    [TestGroup]              VARCHAR (255)  NULL,
    [UnitOfMeasure]          VARCHAR (50)   NULL,
    [Basis]                  VARCHAR (4000) NULL,
    [Application]            VARCHAR (4000) NULL,
    [ActionRequired]         VARCHAR (255)  NULL,
    [BomTestGroup]           VARCHAR (255)  NULL,
    [TestMethodVersion]      VARCHAR (25)   NULL,
    [SubType]                VARCHAR (100)  NULL,
    [MaterialSubType]        VARCHAR (100)  NULL,
    [DataType]               INT            NULL,
    CONSTRAINT [LocalE2PPerfChars_PK_PerfCharId] PRIMARY KEY CLUSTERED ([PerfCharId] ASC),
    CONSTRAINT [FK_Local_E2P_PerfChars_Local_E2P_Received_Component] FOREIGN KEY ([ComponentId]) REFERENCES [dbo].[Local_E2P_Received_Component] ([ComponentId]),
    CONSTRAINT [FK_Local_E2P_PerfChars_Local_E2P_Received_FPP] FOREIGN KEY ([FPPId]) REFERENCES [dbo].[Local_E2P_Received_FPP] ([FPPId])
);

