CREATE TABLE [dbo].[Local_tblWFRequestMaterialOutputDebug] (
    [Id]                    INT              IDENTITY (1, 1) NOT NULL,
    [UNIQUEGUID]            UNIQUEIDENTIFIER NULL,
    [SPID]                  INT              NULL,
    [Message]               VARCHAR (2000)   NULL,
    [EntryOn]               DATETIME         NULL,
    [Selected]              VARCHAR (10)     NULL,
    [Location]              VARCHAR (50)     NULL,
    [MaterialGroup]         VARCHAR (50)     NULL,
    [Material]              VARCHAR (50)     NULL,
    [MaterialDesc]          VARCHAR (50)     NULL,
    [AltMaterial]           VARCHAR (50)     NULL,
    [OrderUOMQty]           VARCHAR (50)     NULL,
    [OrderPalletCnt]        VARCHAR (50)     NULL,
    [StagingCapacityPallet] VARCHAR (50)     NULL,
    [StillNeededPallet]     VARCHAR (50)     NULL,
    [ThresholdPallet]       VARCHAR (50)     NULL,
    [PlannedQty]            VARCHAR (50)     NULL,
    [OpenRequestUOMQty]     VARCHAR (50)     NULL,
    [OpenRequestPalletCnt]  VARCHAR (50)     NULL,
    [MaterialUOM]           VARCHAR (50)     NULL,
    [DocumentHeaderRequest] VARCHAR (50)     NULL,
    [DocumentHeaderCancel]  VARCHAR (50)     NULL,
    [DocumentHeaderCance]   VARCHAR (50)     NULL,
    [MessageHeader]         VARCHAR (50)     NULL,
    [DetailHeader]          VARCHAR (50)     NULL,
    [SESSION_KEY]           VARCHAR (50)     NULL,
    [MESSAGE_ID]            VARCHAR (50)     NULL,
    [TIMESTAMP]             VARCHAR (50)     NULL,
    [ITMCOD]                VARCHAR (50)     NULL,
    [QTY]                   VARCHAR (50)     NULL,
    [TO_LOCATN]             VARCHAR (50)     NULL,
    [PRDORD]                VARCHAR (50)     NULL,
    [SITNAM]                VARCHAR (50)     NULL,
    [SUBSITE]               VARCHAR (50)     NULL,
    [MATREQ]                VARCHAR (50)     NULL,
    [ITMPOS]                VARCHAR (50)     NULL,
    [StagingUOMQty]         VARCHAR (50)     NULL,
    [StagingPalletCnt]      VARCHAR (50)     NULL,
    [PreStagingUOMQty]      VARCHAR (50)     NULL,
    [PreStagingPalletCnt]   VARCHAR (50)     NULL,
    [UserName]              VARCHAR (100)    NULL,
    [OrderPhase]            VARCHAR (100)    NULL
);

