CREATE TABLE [dbo].[Local_eDH_Defects] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [DateFound]          DATETIME       NOT NULL,
    [DateSolved]         DATETIME       NULL,
    [PMOpenDate]         DATETIME       NULL,
    [PMCloseDate]        DATETIME       NULL,
    [SourceEventID]      INT            NULL,
    [SourceRecordID]     BIGINT         NULL,
    [UserName]           NVARCHAR (255) NULL,
    [DefectTypeId]       INT            NULL,
    [DefectComponentId]  INT            NULL,
    [HowFoundId]         INT            NULL,
    [PMNotification]     BIT            NULL,
    [NotificationNum]    NVARCHAR (255) NULL,
    [PMStatus]           NVARCHAR (255) NULL,
    [PriorityId]         INT            NULL,
    [FileURL]            NVARCHAR (255) NULL,
    [CM1]                NVARCHAR (255) NULL,
    [CM2]                NVARCHAR (255) NULL,
    [CM3]                NVARCHAR (255) NULL,
    [Responsibility]     NVARCHAR (255) NULL,
    [WorkPlanId]         INT            NULL,
    [Description]        NVARCHAR (500) NULL,
    [Department]         NVARCHAR (255) NULL,
    [CreatedBy]          NVARCHAR (150) NULL,
    [FoundBy]            NVARCHAR (150) NULL,
    [ClosedBy]           NVARCHAR (150) NULL,
    [FixedBy]            NVARCHAR (150) NULL,
    [OtherFLDescription] NVARCHAR (MAX) NULL,
    [FLId]               INT            NULL,
    [NonEquipment]       BIT            NULL,
    [CILLongDescription] NVARCHAR (MAX) NULL,
    [eDHTeamId]          INT            NULL,
    [Repeat]             BIT            DEFAULT ((0)) NULL,
    [DueDate]            DATETIME       NULL,
    [TeamId]             INT            NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([DefectComponentId]) REFERENCES [dbo].[Local_eDH_List] ([Id]),
    FOREIGN KEY ([DefectTypeId]) REFERENCES [dbo].[Local_eDH_List] ([Id]),
    FOREIGN KEY ([eDHTeamId]) REFERENCES [dbo].[Local_eDH_Team] ([Id]),
    FOREIGN KEY ([FLId]) REFERENCES [dbo].[Local_eDH_FuncLocation] ([FLId]),
    FOREIGN KEY ([HowFoundId]) REFERENCES [dbo].[Local_eDH_List] ([Id]),
    FOREIGN KEY ([PriorityId]) REFERENCES [dbo].[Local_eDH_List] ([Id]),
    FOREIGN KEY ([TeamId]) REFERENCES [dbo].[Local_PG_eCIL_Teams] ([Team_Id]),
    FOREIGN KEY ([WorkPlanId]) REFERENCES [dbo].[Local_eDH_List] ([Id])
);

