CREATE TABLE [dbo].[Local_MPWS_IMPORT_PM_ORDER_LG] (
    [ORDER_ID]         NVARCHAR (255) NULL,
    [ENTRY_TIMESTAMP]  DATETIME       NULL,
    [ORDER_PROD_ID]    NVARCHAR (255) NULL,
    [ORDER_PROD_DESC]  NVARCHAR (255) NULL,
    [ORDER_PROD_QTY]   FLOAT (53)     NULL,
    [ORDER_PROD_UOM]   NVARCHAR (255) NULL,
    [ORDER_TIME]       DATETIME       NULL,
    [SCHED_BEGIN_TIME] DATETIME       NULL,
    [SCHED_END_TIME]   NVARCHAR (255) NULL,
    [ORDER_STATUS]     NVARCHAR (255) NULL,
    [USER_NAME]        NVARCHAR (255) NULL,
    [VERIFIER_NAME]    NVARCHAR (255) NULL,
    [STEP_NAME]        NVARCHAR (255) NULL,
    [STEP_INSTANCE]    FLOAT (53)     NULL,
    [SIGNATURE]        NVARCHAR (255) NULL,
    [CYCLE_SEQ]        NVARCHAR (255) NULL,
    [ORDER_SEQ]        NVARCHAR (255) NULL
);

