CREATE TABLE [dbo].[Local_E2P_Global_PerformanceSpecifications] (
    [PerformanceSpecId]        INT           IDENTITY (1, 1) NOT NULL,
    [ComponentId]              INT           NOT NULL,
    [Characteristic]           VARCHAR (255) NOT NULL,
    [CharacteristicSpecifics]  VARCHAR (255) NULL,
    [ReportType]               VARCHAR (255) NULL,
    [LowerLimit]               VARCHAR (25)  NULL,
    [LowerTarget]              VARCHAR (25)  NULL,
    [Target]                   VARCHAR (25)  NULL,
    [UpperTarget]              VARCHAR (25)  NULL,
    [UpperLimit]               VARCHAR (25)  NULL,
    [UnitOfMeasure]            VARCHAR (255) NULL,
    [ReportToNearest]          VARCHAR (255) NULL,
    [ReleaseCriteria]          VARCHAR (255) NULL,
    [ActionRequired]           VARCHAR (255) NULL,
    [UpperRoutineReleaseLimit] VARCHAR (25)  NULL,
    [LowerRoutineReleaseLimit] VARCHAR (25)  NULL,
    [PlantTestingLevel]        VARCHAR (25)  NULL,
    [Sampling]                 VARCHAR (255) NULL,
    [Subgroup]                 VARCHAR (15)  NULL,
    [TestMethodOrigin]         VARCHAR (255) NULL,
    [TestMethodLogic]          VARCHAR (255) NULL,
    [TestMethodNumber]         VARCHAR (255) NULL,
    [TestMethodSpecifics]      VARCHAR (255) NULL,
    [Criticality]              VARCHAR (255) NULL,
    [Basis]                    VARCHAR (255) NULL,
    [Application]              VARCHAR (255) NULL,
    CONSTRAINT [LocalE2PGlobalPerformanceSpecifications_PK_PerformanceSpecId] PRIMARY KEY CLUSTERED ([PerformanceSpecId] ASC),
    CONSTRAINT [FK_Local_E2P_Global_PerformanceSpecifications_Local_E2P_Global_Components] FOREIGN KEY ([ComponentId]) REFERENCES [dbo].[Local_E2P_Global_Components] ([ComponentId])
);

