CREATE TABLE [dbo].[Local_tblMSG3] (
    [Id]          INT           IDENTITY (1, 1) NOT NULL,
    [MSGTYP]      VARCHAR (255) NULL,
    [MSGINT]      VARCHAR (255) NULL,
    [TRXCOD]      VARCHAR (255) NULL,
    [SUBSIT]      VARCHAR (255) NULL,
    [FROM_LOC]    VARCHAR (255) NULL,
    [TO_LOC]      VARCHAR (250) NULL,
    [ITMCLS]      VARCHAR (250) NULL,
    [ITMCOD]      VARCHAR (255) NULL,
    [CODDAT]      VARCHAR (255) NULL,
    [PRODAT]      VARCHAR (255) NULL,
    [EXPDAT]      VARCHAR (255) NULL,
    [CASQTY]      VARCHAR (255) NULL,
    [ULPALL]      VARCHAR (255) NULL,
    [ULIDCD]      VARCHAR (255) NULL,
    [UL_STACOD]   VARCHAR (255) NULL,
    [PRDORD]      VARCHAR (255) NULL,
    [BYPCOD]      VARCHAR (255) NULL,
    [SLDFLG]      VARCHAR (255) NULL,
    [DELVCD]      VARCHAR (255) NULL,
    [MACHID]      VARCHAR (255) NULL,
    [TEAMID]      VARCHAR (255) NULL,
    [TRNOVR]      VARCHAR (255) NULL,
    [FRTBCK]      VARCHAR (255) NULL,
    [PRTLBL]      VARCHAR (255) NULL,
    [HOST_ID]     VARCHAR (255) NULL,
    [HOST_REC]    VARCHAR (255) NULL,
    [MSTAMP]      VARCHAR (255) NULL,
    [ERRCOD]      VARCHAR (255) NULL,
    [ERRDSC]      VARCHAR (255) NULL,
    [CTRL_DATE]   VARCHAR (255) NULL,
    [CTRL_USER]   VARCHAR (255) NULL,
    [BASE_ULIDCD] VARCHAR (255) NULL,
    [TO_ULIDCD]   VARCHAR (255) NULL,
    [CTLGRP]      VARCHAR (255) NULL,
    [ENTRY_ON]    DATETIME      NULL
);


GO
CREATE NONCLUSTERED INDEX [tblMSG3_entry_on]
    ON [dbo].[Local_tblMSG3]([ENTRY_ON] ASC);

