CREATE TABLE [dbo].[Local_eDH_Defects_bck] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [DateFound]          DATETIME       NOT NULL,
    [DateSolved]         DATETIME       NULL,
    [PMOpenDate]         DATETIME       NULL,
    [PMCloseDate]        DATETIME       NULL,
    [SourceEventID]      INT            NULL,
    [SourceRecordID]     INT            NULL,
    [UserName]           NVARCHAR (255) NULL,
    [DefectTypeId]       INT            NULL,
    [DefectComponentId]  INT            NULL,
    [HowFoundId]         INT            NULL,
    [PMNotification]     BIT            NULL,
    [NotificationNum]    NVARCHAR (255) NULL,
    [PMStatus]           NVARCHAR (255) NULL,
    [PriorityId]         INT            NULL,
    [FileURL]            NVARCHAR (255) NULL,
    [CM1]                NVARCHAR (255) NULL,
    [CM2]                NVARCHAR (255) NULL,
    [CM3]                NVARCHAR (255) NULL,
    [Responsibility]     NVARCHAR (255) NULL,
    [WorkPlanId]         INT            NULL,
    [Description]        NVARCHAR (255) NULL,
    [Department]         NVARCHAR (255) NULL,
    [CreatedBy]          NVARCHAR (150) NULL,
    [FoundBy]            NVARCHAR (150) NULL,
    [ClosedBy]           NVARCHAR (150) NULL,
    [FixedBy]            NVARCHAR (150) NULL,
    [OtherFLDescription] NVARCHAR (MAX) NULL,
    [FLId]               INT            NULL,
    [NonEquipment]       BIT            NULL,
    [CILLongDescription] NVARCHAR (MAX) NULL
);

