CREATE TABLE [ncr].[defect_history] (
    [id]                                BIGINT         IDENTITY (1, 1) NOT NULL,
    [created_by]                        VARCHAR (255)  NULL,
    [created_on]                        DATETIME2 (7)  NULL,
    [last_modified_by]                  VARCHAR (255)  NULL,
    [last_modified_on]                  DATETIME2 (7)  NULL,
    [version]                           INT            NULL,
    [column_updated_bitmask]            VARCHAR (15)   NULL,
    [dbtt_id]                           INT            NULL,
    [modified_on]                       DATETIME2 (7)  NULL,
    [affected_object_id]                VARCHAR (255)  NULL,
    [affected_quantity]                 FLOAT (53)     NULL,
    [affected_quantity_unit_of_measure] VARCHAR (255)  NULL,
    [comment_id]                        VARCHAR (255)  NULL,
    [defect_reason_level1_id]           VARCHAR (255)  NULL,
    [defect_reason_level2_id]           VARCHAR (255)  NULL,
    [defect_reason_level3_id]           VARCHAR (255)  NULL,
    [defect_reason_level4_id]           VARCHAR (255)  NULL,
    [defect_type_id]                    BIGINT         NULL,
    [description]                       NVARCHAR (MAX) NULL,
    [location_id]                       VARCHAR (255)  NULL,
    [location_type]                     VARCHAR (255)  NULL,
    [non_conformance_id]                BIGINT         NULL,
    [reported_by]                       VARCHAR (255)  NULL,
    [status]                            VARCHAR (255)  NULL,
    [summary]                           NVARCHAR (255) NULL,
    [defect_id]                         BIGINT         NULL,
    [affected_object_type]              VARCHAR (255)  NULL,
    [defect_context_type]               NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK__defect_hi__defec__4D94879B] FOREIGN KEY ([defect_id]) REFERENCES [ncr].[defect] ([id])
);

